### ISSUE TITLE
Demo content import throws errors

### ISSUE THREAD

**Issue by puikinsh** [puikinsh/shapely#102]
<img width="1110" alt="screenshot 2016-12-10 09 28 28" src="https://cloud.githubusercontent.com/assets/3451398/21071992/19d0f4fe-bebc-11e6-8323-f744ff9a8e1f.png">

**Comment by cristianraiber** [comment]
@c0sm1n87 - please investigate. From what I remember, the demo content tab should have been removed

**Comment by cristianraiber** [comment]
Marking as invalid, test wasn't using the latest theme version.

**Comment by c0sm1n87** [comment]
@cristianraiber the demo content tab was not removed, it's brought in by the shapely companion plugin. I'll need to find a way to add it in the required action tab without crossing plugin territory

**Comment by cristianraiber** [comment]
@c0sm1n87 - I've added this on #95
