### ISSUE TITLE
Widget improvement issue

### ISSUE THREAD

**Issue by cristianraiber** [puikinsh/shapely#105]
For this set-up, the image (`<img>` tag) doesn't have bootstrap classes added. Also, images that have the class `.cast-shadow` applied to them, should also add a margin-bottom of 10px to properly accommodate the box-shadow being cast below it. In lack of clearfix, scenarios like the ones in the image will happen.  

**Note:** This issue happens for both top & bottom layout scenarios. 

---

![image](https://cloud.githubusercontent.com/assets/7841556/21105977/f80cad2e-c094-11e6-9a53-c2a29350d999.png)

---

**Comment by cristianraiber** [comment]
@c0sm1n87 - this doesn't seem to be fixed. 

![image](https://cloud.githubusercontent.com/assets/7841556/21141397/982d663a-c145-11e6-9156-ca1ef658a4dd.png)

**Comment by c0sm1n87** [comment]
please pull the latest version, clear cache and try again. i tested this as in your scenario.

**Comment by cristianraiber** [comment]
This has been fixed.
