### ISSUE TITLE
Mobile Blog posts doesn't work

### ISSUE THREAD

**Issue by cristiantanase2016** [puikinsh/shapely#117]
Reference here:

https://colorlib.com/wp/forums/topic/mobile-blog-doesnt-work/

I’ve just looked at my blog on my phone and I can’t open any of the individual blog posts from the phone? I’ve tried it in both Google Chrome and Safari on the phone and neither allows me to open individual posts from the blog main page. The main Blog post page shows four posts at a time but will only allow me to open the last one.
The URL for my blog is: http://northphoto.uk/blog

It works fine on the computer, it just doesn’t seem to work on my phone.

**Comment by cristianraiber** [comment]
@cristiantanase2016 - any ideas as to which phone was used to perform the testing?

**Comment by cristiantanase2016** [comment]
Iphone 5, (Galaxy s7edge y Galaxy S6 tested by me and didn't work)

**Comment by cristianraiber** [comment]
@cristiantanase2016 - could you please download & install the version from this git and test with your cellphone, see if it works? The blog just got overhauled and this issue shouldn't be present anymore.

**Comment by giucu91** [comment]
It's working with Shapely 1.1.2 version. Checked with iPhone 7. The version from WP.org repo

**Comment by cristianraiber** [comment]
Just tested this from iPhone 7+ & Nexus 6P. Works fine.
