### ISSUE TITLE
Translation ready

### ISSUE THREAD

**Issue by sakinshrestha** [puikinsh/shapely#118]
* All theme text strings are to be translatable. Missing in 
     * header.php (line: 36) 
     * team-page-bc.php (line: 91, 108)
     * team-page.php ( 91, 106, 108) 
     * footer.php
     * and more 
* This might not be valid for your custom theme developing for client. But it's good to look at https://developer.wordpress.org/themes/functionality/internationalization/

**Comment by cristianraiber** [comment]
@sakinshrestha I think you might have posted this in the wrong repo?

**Comment by sakinshrestha** [comment]
oh sorry late night jet lag...

**Comment by cristianraiber** [comment]
No worries
