### ISSUE TITLE
Escaping Translated Strings: Recommended escaping translation strings

### ISSUE THREAD

**Issue by sakinshrestha** [puikinsh/shapely#120]
* All translation functions must be escaped as sometimes an improper translation may break the html. You have done it in some places.
* E.g:
    * Almost all instances of `__()`/``_e()`` need to be `esc_html__()`/`esc_html_e()`
        * `functions.php` line 173 becomes
            `'name'          => esc_html__( 'Sidebar', 'shapely' ),`
    * `esc_attr__()` where used as attribute values
    * passed via `wp_kses()` if some html elements are required

**Comment by cristianraiber** [comment]
Fixed in: 188b1d659a6a3f777e91e37b3e20572394338b70
