### ISSUE TITLE
Escaping issues

### ISSUE THREAD

**Issue by sakinshrestha** [puikinsh/shapely#122]
* Escape `admin_url` in line 196 in `navwalker.php` using `esc_url`
* Escape `get_search_query()` in `extras.php` line 83 using `esc_attr`

**Comment by justintadlock** [comment]
In `inc/class-shapely-related-posts.php`:

* 173 - `$limit` - `esc_html()`
* 173 - `$auto_play` - `esc_html()`

**Comment by cristianraiber** [comment]
Fixed in: 188b1d659a6a3f777e91e37b3e20572394338b70
