### ISSUE TITLE
Unnecessary escaping

### ISSUE THREAD

**Issue by sakinshrestha** [puikinsh/shapely#124]
* No need to escape `the_title_attribute()` as it is already escaped
 * line 39 in `archive-jetpack-portfolio.php`
 * line 14 in `template-parts\content-page.php`
* No need to escape hardcoded image sources
 * line 183 `inc\class-shapely-related-posts.php`

**Comment by cristianraiber** [comment]
Fixed in: 188b1d659a6a3f777e91e37b3e20572394338b70
