### ISSUE TITLE
Design Issue: Menu

### ISSUE THREAD

**Issue by sakinshrestha** [puikinsh/shapely#126]
* When using long menu, the menu items that doesn't fit in header area and search gets hidden. Theme should support long menu items as well. 
* Check out screenshot of long menu items
<img width="1197" alt="menu-items-search-hidden" src="https://cloud.githubusercontent.com/assets/9452203/21799234/752db624-d740-11e6-9658-068b235452e3.png">
* Check out screenshot of short menu items
<img width="1215" alt="short-menu-items" src="https://cloud.githubusercontent.com/assets/9452203/21799298/b8845ec8-d740-11e6-9b6d-6dcb5b436887.png">

**Comment by justintadlock** [comment]
Or, at least make a note that this is a design limitation in your `readme` file.  Such limitations are required on .ORG to be noted.

**Comment by cristianraiber** [comment]
Fixed in: 188b1d659a6a3f777e91e37b3e20572394338b70
