### ISSUE TITLE
Static Front Page with home page template

### ISSUE THREAD

**Issue by sakinshrestha** [puikinsh/shapely#127]
* Static front page with Home Page template is not showing any content. It should show the page content when selecting page in Static front page. If you are not going to show then you need to add that information in your readme.txt file
* Design issue: when I add in widgets in "Homepage" widget area, the design of front page is not good. It full width and has margin issues between widgets. See this screenshot 
![margin-issues](https://cloud.githubusercontent.com/assets/9452203/21816605/c50bd93a-d788-11e6-9c7b-a313699f9468.png)

**Comment by cristianraiber** [comment]
Fixed in: 188b1d659a6a3f777e91e37b3e20572394338b70
