### ISSUE TITLE
Use post_class()

### ISSUE THREAD

**Issue by justintadlock** [puikinsh/shapely#128]
In the following files, you must use the `post_class()` function to output the post class.  If you need custom classes, you can pass them in directly, such as `post_class( 'post-content example' )` or filter the `post_class` hook.

* `template-parts/content.php`
* `template-parts/content-grid-small.php`
* `template-parts/content-grid-wide.php`
* `template-parts/content-search.php`

_We should've caught this in the first round, but it's not something we usually manually check because the WP Theme Check plugin typically picks it up.  It didn't notice it because you use `post_class()` elsewhere in the theme._

**Comment by cristianraiber** [comment]
Fixed in: 188b1d659a6a3f777e91e37b3e20572394338b70
