### ISSUE TITLE
Blog name text / theme mod

### ISSUE THREAD

**Issue by justintadlock** [puikinsh/shapely#134]
This line is a bit odd in `inc/extras.php` (line 651).  It's one of those things that will technically work, so not immediately apparent that it's a bug.

```
_e( ( get_theme_mod( 'blog_name' ) ) ? get_theme_mod( 'blog_name' ) : 'Blog', 'shapely' );
```

It should be something like this:

```
echo esc_html( get_theme_mod( 'blog_name' ) ? get_theme_mod( 'blog_name' ) : __( 'Blog', 'shapely' ) );
```

`_e()` shouldn't wrap the entire thing because translation parsers can only pick up strings.

**Comment by cristianraiber** [comment]
Fixed here: https://github.com/puikinsh/shapely/pull/149
