### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by justintadlock** [puikinsh/shapely#135]
Just a couple of minor notes here for making sure this passes .ORG.

**Font Awesome license:**

Font Awesome's font is under the SIL OFL.  However, its CSS is under the MIT.  You'll want to note both in your `readme.txt` since you're including both in the theme.

```
Font Awesome 4.5.0 by @davegandy - http://fontawesome.io - @fontawesome
License - http://fontawesome.io/license (Font: SIL OFL 1.1, CSS: MIT License)
```

**Image in screenshot:**

If the image in the screenshot is a third-party image, make sure it's GPL-compatible and list its copyright and license info.

If you own the image, just make a small note of it in the readme to help the reviewer out.

**Comment by cristianraiber** [comment]
https://github.com/puikinsh/shapely/pull/149
