### ISSUE TITLE
Injecting linked number into customizer via JS

### ISSUE THREAD

**Issue by justintadlock** [puikinsh/shapely#136]
The theme directory has a more recent rule that themes are not allowed to inject elements into the customizer via JS.  This was primarily meant for stopping people from injecting upsell links in odd places and breaking the customizer UI.

Your _welcome screen customizer JS_ definitely breaks that rule by injecting a linked number.  Personally, I feel like this is minor enough to not be an issue in this particular case.  However, the TRT might disagree.  So, this is more of a heads up.  You can always bring it up with the team to see how they feel about allowing it.

![2-customizer-number](https://cloud.githubusercontent.com/assets/1816309/21853308/38e73428-d7dc-11e6-8d12-4d479a033e62.png)

The proposed alternative is to use the Customizer API to add such an item, which you already know how to do.  I've built something for this primarily meant to be used for upsell links: https://github.com/justintadlock/trt-customizer-pro I just feel like it's a bit overkill for a tiny number.

**Comment by cristianraiber** [comment]
@giucu91 - this should be fixed by adding the newest version of Epsilon Framework.

**Comment by cristianraiber** [comment]
This has been fixed by adding the latest version of https://github.com/MachoThemes/epsilon-framework/
