### ISSUE TITLE
Design: Attachment pages

### ISSUE THREAD

**Issue by justintadlock** [puikinsh/shapely#137]
While not a requirement for .ORG (other than having a working attachment page), I'd love to see some attention given to attachment pages on the front end.  Right now, attachments just use the single post template and are not anything special.

![2-attachment](https://cloud.githubusercontent.com/assets/1816309/21854151/4c301308-d7df-11e6-9e40-7b89e31efb5b.png)

I'd like to see a full-size image.  I'd remove the byline, author bio, and related posts sections.  Those are the things I'd do at minimum.

Then, for something extra, you can always add navigation between attachments for the post.  And, you can display attachment metadata.  This is something that goes _above and beyond_, but I have a whole bunch of attachment/media functionality that you're always free to incorporate into your themes:

* https://github.com/justintadlock/hybrid-core/blob/3.0/inc/template-media.php
* https://github.com/justintadlock/hybrid-core/blob/3.0/inc/class-media-meta.php
* https://github.com/justintadlock/hybrid-core/blob/3.0/inc/class-media-meta-factory.php

WP stores a lot of metadata for images, videos, and audio files nowadays.  They can be fun to play around with and help attachment pages stand out.

At the very least though, I'd like to see the image attachment pages (most commonly used) given some love.

**Comment by cristianraiber** [comment]
Fixed here: https://github.com/puikinsh/shapely/pull/151
