### ISSUE TITLE
Unnecessary wp_reset_query() call

### ISSUE THREAD

**Issue by justintadlock** [puikinsh/shapely#138]
You don't need the call to `wp_reset_query()` here (it should only be used in conjuction with `query_posts()`).  The `wp_reset_postdata()` call is correct.

From `inc/class-shapely-related-posts.php` (lines 123 and 213):

```
// reset post query
wp_reset_postdata();
wp_reset_query();
```

**Comment by cristianraiber** [comment]
Fixed here: https://github.com/puikinsh/shapely/pull/149
