### ISSUE TITLE
Gap between sections on homepage

### ISSUE THREAD

**Issue by jsaka** [puikinsh/shapely#139]
Hello,

I installed the theme and demo data, on homepage seems there's a white gap above and below the "Small Parallax Section". Seems the same problem on other sections too. Is it the case, or I did something wrong?

Thanks.

**Comment by cristianraiber** [comment]
@jsaka - what's your theme version, please?

**Comment by jsaka** [comment]
My theme version is 1.1.0. I just download it today from here. Also installed the Companion, downloaded from here:
https://colorlib.com/wp/forums/topic/beta-testing-new-version-shapely/

But after I press "Import data" button in the Companion, seems only widgets are imported, but not demo posts or pages. I haven't switched on "Testimonial" and "Portfolio" feature of Jetpack, before I press the "Import data" button, not sure if it's the problem. Then, I can't find the "Import data" button any longer (BTW, how I can make the button appear again, or let it to remove all previous imported data and import again?)

So I download demo data from here and import them. May be it's not the latest demo data? Not sure if this causes the problem:
https://cdn.colorlib.com/wp/wp-content/uploads/sites/2/shapely-demo-content.zip

Thanks.

**Comment by cristianraiber** [comment]
@jsaka - yep, part of the problem is the fact that you didn't have the JetPack Testimonials & Portfolio Custom Post Types activated before actually importing the demo data.

**Comment by jsaka** [comment]
I see. Then is the demo data from the link below outdated?
https://cdn.colorlib.com/wp/wp-content/uploads/sites/2/shapely-demo-content.zip

Or what causes the white gap issue I mentioned in the first message?

**Comment by cristianraiber** [comment]
Could we get your site URL, to have a look around? 

Also, what browser / screen resolution did you use?

**Comment by jsaka** [comment]
I've just put the site link here (as want to put in private message), please check, thanks.
https://colorlib.com/wp/forums/topic/gap-between-sections-on-homepage/#post-84450

**Comment by ezraholm50** [comment]
Is this related to #110 perhaps?

**Comment by cristianraiber** [comment]
This doesn't seem to be happening anymore.
