### ISSUE TITLE
Blog Template in Blog Settings

### ISSUE THREAD

**Issue by jsaka** [puikinsh/shapely#140]
I've done the following setting. What is supposed to be the change of this option, is it to set the Blog post default template? I've set it but I can't aware of any change.

Under "Appearance > Customize": Shapely Options > Blog Settings, set "Blog Template" to "No Sidebar"

**Comment by cristianraiber** [comment]
@jsaka - this setting remove the blog archive sidebar.

**Comment by jsaka** [comment]
I see. Then where I can do the settings for the "default template" of Blog posts?

**Comment by cristianraiber** [comment]
What do you mean by "Default template"? Are you referring to the blog archive or single blog posts layout?

Cristian.

**Comment by jsaka** [comment]
I meant the Single Blog posts layout. I can choose "Default Template" when I edit a post. Thinking where I can define the "Default Template"?

**Comment by cristianraiber** [comment]
@giucu91 - this works as intended, but let's add one more setting here. Basically, I want to be able for users to define the 'default' blog index / single post template from the Customizer. Currently, it's only possible to define the default one for the blog, as a whole. No user control.
