### ISSUE TITLE
Demo content or some other issue? 

### ISSUE THREAD

**Issue by puikinsh** [puikinsh/shapely#144]
Is it an outdated demo since widgets have been moved to a plugin or something else? 

https://colorlib.com/wp/forums/topic/shapely-theme-activated-but-cannot-import-widgets/

**Comment by cristianraiber** [comment]
WP 4.7.1 managed to "break" the WP Importer / Exporter plugin. And many others. The solution is to also install this plugin: https://wordpress.org/plugins/disable-real-mime-check/ and then WP Widget Importer / Exporter will work just fine.

**Comment by cristianraiber** [comment]
Also, see this trac ticket: https://core.trac.wordpress.org/ticket/39550 

Should be fixed in WP 4.7.2.

**Comment by yotawsh** [comment]
I have attempted what is requested above with no luck.

**Comment by cristianraiber** [comment]
@yotawsh - what version of WP / Shapely / Widget Importer & Exporter & Shapely companion are you running?

**Comment by yotawsh** [comment]
Shapely companion was the missing link – thx!

**Comment by cristianraiber** [comment]
Awesome.

**Comment by Kr4ntz** [comment]
give @yotawsh a beer! cheers!
