### ISSUE TITLE
Dailed-to-load-error-on-a-css-file

### ISSUE THREAD

**Issue by cristiantanase2016** [puikinsh/shapely#148]
See reference here:

https://colorlib.com/wp/forums/topic/strange-failed-to-load-error-on-a-css-file/

Hi everybody,
on my travelify based website, when I check the console of the developer tool in Chrome, I get this message:
http://www.refiascone.it/wp-content/themes/travelify/inc/css/bootstrap.min.css?ver=4.7.1 Failed to load resource: the server responded with a status of 404 (Not Found).
Thing is I don’t know why the theme it’s even looking for this css which is not even supposed to be part of the package. Any guess?

**Comment by puikinsh** [comment]
User has tried to combine Sparkling with Travelify as you can see from source code. Maybe it is just cache but this has nothing to do with theme itself. And also you opened an issue for Travelfiy  theme on Shapely repo. 

<img width="1479" alt="screenshot 2017-01-26 10 52 38" src="https://cloud.githubusercontent.com/assets/3451398/22325193/a431a18e-e3b5-11e6-9cbd-48a53506210b.png">
