### ISSUE TITLE
Invalid Argument on Portfolio pages.

### ISSUE THREAD

**Issue by laranz** [puikinsh/shapely#153]
On portfolio page, we're getting an error appearing when we mouse over the various portfolio images:
implode(): Invalid arguments passed in archive-jetpack-portfolio.php on line 46 when wp_debug is turned on.

1. Create a new portfolio, set the project type. ( turn on WP_DEBUG )
2. view portfolio archive page and hover the thumbnail.

Regards,

**Comment by cristianraiber** [comment]
Fixed here: https://github.com/puikinsh/shapely/pull/154
