### ISSUE TITLE
Plugin shortcode not working

### ISSUE THREAD

**Issue by jinhi** [puikinsh/shapely#156]
I was able to add a table plugin in the previous version of Shapely. And it looked great! The new version of Shapely just shows the coding:

In the same URL, look for the SCHEDULE widget.

http://69.89.31.185/~woodstu0/dojo/

When I first built this site, I used the old version of Shapely. You'll see under the SCHEDULE part that the table plugin works. I would continue to use the old version, but since the update, it's become very unstable. 

http://www.outerworldrecords.com/dojo/

Please help!

**Comment by jinhi** [comment]
Any update on this one?

**Comment by giucu91** [comment]
Hello @jinhi,

Can you please tell me the name of plugin in order to test the theme with it ?

Thank you,
George.
