### ISSUE TITLE
Customize Logo and header size.

### ISSUE THREAD

**Issue by laranz** [puikinsh/shapely#158]
https://colorlib.com/wp/forums/topic/logo-size-and-header-space-mods/

Few user suggest this feature, and I think it is a handy feature too :) 

Also in the new version, the logo get squished we need to prevent that too

**Comment by c0sm1n87** [comment]
We`ll think for a way to do this in the next update

**Comment by cristianraiber** [comment]
@giucu91 - this could be handled with Epsilon range sliders. Setting a max-height & max-width for the logo. These values could be changed by the end user to accommodate their logos.

**Comment by laranz** [comment]
@cristianraiber  and @c0sm1n87 guys, When this feature will be added?

**Comment by cristianraiber** [comment]
@laranz - how many users are asking for this?

**Comment by laranz** [comment]
5 Threads I handled, and hopefully more than 7 users request this.. and also it is a handy feature that needs to be added IMO. 👍

**Comment by cristianraiber** [comment]
@laranz - thanks for this. Will make sure it gets handled on next theme update.

**Comment by cristianraiber** [comment]
@giucu91 - let's see what we can come up with here to make this better for users.
