### ISSUE TITLE
Author's Email shouldn't display on Author Bio area.

### ISSUE THREAD

**Issue by laranz** [puikinsh/shapely#159]
We need to ask their permission in Appearance -> Customize.
 before doing displaying the email ID  via some options, because showing email ID in public is sensitive for some users.

![image](https://cloud.githubusercontent.com/assets/208945/23250064/78dbe598-f9cd-11e6-9124-2b4195b84b36.png)

**Comment by cristianraiber** [comment]
This is now locked behind a toggle in Theme Options -> Blog Settings -> Single Post settings.
