### ISSUE TITLE
Few new options

### ISSUE THREAD

**Issue by puikinsh** [puikinsh/shapely#16]
- hide post/page title next to breadcrumbs while keeping breadcrumbs in place
- hide post/page title while leaving title which you can see next to breadcrumbs in place

**Comment by cristianraiber** [comment]
@puikinsh - this is more of a design decision. How should the header bar look once the post title (the one that gives the height for the whole area) look? Do you want it to collapse to the height of the breadcrumbs menu or keep it's original height? 

@c0sm1n87 - we could add some toggles in: Customize- > Shapely Options -> Main Options

**Comment by cristianraiber** [comment]
@c0sm1n87 - Checkbox to toggle, please.

![image](https://cloud.githubusercontent.com/assets/7841556/21106387/961da710-c096-11e6-8ee5-c8d488aad6b4.png)

**Comment by cristianraiber** [comment]
The above screenshot is invalid as those options are actually coming from Yoast and not from within the theme.
