### ISSUE TITLE
Blog author bio gravatar image on Retina(HiDPI) displays

### ISSUE THREAD

**Issue by puikinsh** [puikinsh/shapely#160]
Either gravatar image should be smaller or dividing line should be moved to the right. Please see a screenshot: 
![screenshot-2017-02-23-10 17 12](https://cloud.githubusercontent.com/assets/3451398/23250448/dfe064a6-f9b1-11e6-8ce9-a723de12602a.jpg)

Would be great if someone could test if it happens only on Retina displays with x2 image size.

**Comment by puikinsh** [comment]
Where is the fix for this as it sill doesn't show up correctly on the version that is available on the repo?

**Comment by cristianraiber** [comment]
Have you tried the version from here? That's the one I'm testing on.

**Comment by puikinsh** [comment]
Do you use Retina(HiDPI) display?

**Comment by cristianraiber** [comment]
I don't think it's a HIDPI related issue. This was just taken now from Shapely demo, hosted on Colorlib. Not using a HiDPI display, but will test with one sometime today as well. 

![image](https://cloud.githubusercontent.com/assets/7841556/26304304/6c1aec30-3ef3-11e7-850d-36f881d98714.png)

**Comment by AnaMaican** [comment]
HiDPI screenshot. This issue's been fixed, however, #181 has been created. 


![image](https://cloud.githubusercontent.com/assets/23457094/26304435/3d345682-3ee3-11e7-8cd5-7731d76d75aa.png)

**Comment by puikinsh** [comment]
Ok, it appears you have a different version for testing because the latest version on Github does show author bio but the image still has a line on it.

**Comment by cristianraiber** [comment]
Latest development version is on our fork, here: https://github.com/machothemes/shapely. We're only pushing to your repo once we have something semi-final / working as people usually download from your GitHub repository more often than I was expecting :)
