### ISSUE TITLE
Allow simple HTML inside the widget content.

### ISSUE THREAD

**Issue by laranz** [puikinsh/shapely#162]
Requested here:

https://colorlib.com/wp/forums/topic/enabling-html-tags-in-widgets-or-test-areas/#post-88872
https://colorlib.com/wp/forums/topic/html-tagsplugins-not-working/#post-88799
https://colorlib.com/wp/forums/topic/multi-language-plugins-recommended/#post-88870

**Comment by giucu91** [comment]
Duplicate of #164 and #155
