### ISSUE TITLE
Parallax on Mobile.

### ISSUE THREAD

**Issue by laranz** [puikinsh/shapely#163]
Few user complaint about that,

https://colorlib.com/wp/forums/topic/responsive-doesnt-respond-well/#post-88671
https://colorlib.com/wp/forums/topic/shapely-home-page-parallax-not-working-on-iphone-ipad/

Yeah, I know iOS have some issue with the parallax backgrounds, and there are some workarounds for that, can we include anyone into shapely?

**Comment by cristianraiber** [comment]
@laranz - unfortunately, this can't be fixed anytime soon. It's actually an issue with the Parallax JS script used in this theme (which, surprisingly, is the most widely used one) and it's a bug from within the script that hasn't yet been addressed.

**Comment by cristianraiber** [comment]
Leaving this ticket open in case anyone else comes onto the repo and is looking for an explanation to this issue.
