### ISSUE TITLE
HTML tags not working in FEATURES widget.

### ISSUE THREAD

**Issue by jinhi** [puikinsh/shapely#164]
Simple HTML tags now seem to work on PARALLAX widgets. Unfortunately, they are still not working in the FEATURES widget.

http://catskillpines.com/pines/#shapely_home_features-2

I've attached a screengrab. Hoping this will be a quick fix.

Best,
Jinhi
![trasnhme](https://cloud.githubusercontent.com/assets/25909536/23462901/a489671c-fe5d-11e6-93cb-c6d62b2601ec.png)

**Comment by cristianraiber** [comment]
@jinhi - This has been fixed and an update to address this issue will be released shortly. Keep an eye out for it in your WP admin Dashboard.
