### ISSUE TITLE
[Enchancement] Support for Vimeo in Homepage Video Widget

### ISSUE THREAD

**Issue by laranz** [puikinsh/shapely#167]
For now we only supports YouTube, it is good to support other video providers, say Vimeo.

https://colorlib.com/wp/forums/topic/support-for-vimeo-in-homepage-video-widget/

**Comment by cristianraiber** [comment]
@giucu91 - please see this.

**Comment by mplusb** [comment]
Video videos do not change their height based on the widget's settings.
