### ISSUE TITLE
[Enchancement] Blog page "Read more"  button bg color

### ISSUE THREAD

**Issue by laranz** [puikinsh/shapely#168]
Blog page "Read more"  button bg color don't take accent color, it is always violet

![image](https://cloud.githubusercontent.com/assets/208945/24183588/493ab076-0eef-11e7-93c8-2ba90772a15a.png)

**Comment by cristianraiber** [comment]
@giucu91 - also, there's a small capitalization issue here; the widget's default title is `recent Posts` while it should be `Recent Posts`.
