### ISSUE TITLE
Skip logo's crop to use SVG images

### ISSUE THREAD

**Issue by vanessametonini** [puikinsh/shapely#169]
Hi folks.

There is anyway to skip logo's crop?

I'm already using a plugin to upload svg files, but there is a requirement to always crop the logo image, and obviously it not applies for svg. It is blocking me to keep on it.

thanks

**Comment by cristianraiber** [comment]
@vanessametonini - You should be able to hit the 'skip cropping' button. Isn't it showing up for you?

**Comment by vanessametonini** [comment]
Hi @cristianraiber thanks for answer.  

It isn't showing. Both for png or svg files.  

**png**  
![png](https://cloud.githubusercontent.com/assets/3089882/24368324/5f3b4cae-12f6-11e7-9266-aebb5728e203.png)

**svg**  
![svg](https://cloud.githubusercontent.com/assets/3089882/24368330/61bcaa68-12f6-11e7-8a19-9433e156f091.png)

**Comment by vanessametonini** [comment]
I'm trying to find how to hack the js to allow me to use the image as it. But that is not a sustainable solution 😓

**Comment by cristianraiber** [comment]
@giucu91 - please look into this.

**Comment by laranz** [comment]
@vanessametonini you can try this, https://colorlib.com/wp/forums/topic/how-to-increase-the-size-of-logo/#post-88586 the trick for "Skip Crop" button resides in the flex-width and flex-height.

**Comment by vanessametonini** [comment]
@laranz thanks I'll try soon

**Comment by vanessametonini** [comment]
Folks, thanks a lot for the help. The solution worked perfectly.
I've published the code, if someone needs in future.
https://github.com/vanessametonini/upwit_cities_for_everyone/tree/master/shapely-child
