### ISSUE TITLE
Theme Seems to break other parallax plugins

### ISSUE THREAD

**Issue by MossP** [puikinsh/shapely#17]
Trying to install other parallax plugins of forge page builder to any of the blog posts results in the parallax not working in the other plugins. Changing the theme to any other and the functionality is restored.

**Comment by c0sm1n87** [comment]
i've tested this scenario (added a parallax section in forge builder on a page that has a shapely parallax widget), but as far as I can see - everything is in order.

**Comment by cristianraiber** [comment]
Same here. Marking as invalid. If this problem resurfaces, we'll reopen it.
