### ISSUE TITLE
Modifying the shop with woocommerce

### ISSUE THREAD

**Issue by thunder772** [puikinsh/shapely#174]
Hi, i install this beauty theme and woocommerce, i trying modify the page "shop" but only see the products, no see the categories, searchs and sidebars, how i can see this?

u can look here: http://sobho.com/tienda/

thanks for help me!!!!

PD: how i can integrate woocommerce with shapely?

**Comment by c0sm1n87** [comment]
Test WooCommerce standard widgets, e.g. Price Filter Widget is really strange

**Comment by c0sm1n87** [comment]
JS conflict is preventing Range Slider to initialize in some cases

**Comment by c0sm1n87** [comment]
JS Conflig removed but the price filter is not initiating. Apparently this problem is generated by WooCommerce, not the theme.
