### ISSUE TITLE
Sidebar option missing?

### ISSUE THREAD

**Issue by TimVNL** [puikinsh/shapely#176]
Hi,

Where is the option to hide the sidebar on a single post? It ws in older version 1.1.0 to be exact

![sidebar-setting-missing](https://cloud.githubusercontent.com/assets/5219523/25740375/8f5d6ca6-3186-11e7-98b1-f804f8c13da6.png)

I can't find the option the Blog Template option only sets the template for the posts overview.

I Can set the template per post but I global option would be nice :)

**Comment by cristianraiber** [comment]
@giucu91 - please see this.

**Comment by giucu91** [comment]
Hello @TimVNL in the new version of Shapely ( 1.1.5 ) the default template from single post will be the template selected in customizer for blog page. Also this is a duplicate for #140 .
