### ISSUE TITLE
Upgrade Epsilon FW & add it as a sub-module

### ISSUE THREAD

**Issue by cristianraiber** [puikinsh/shapely#178]
^ as the title says

**Comment by cristianraiber** [comment]
@giucu91 - this doesn't seem to be implemented. I Just checked shapely-companion, and it seems that Epsilon FW is added directly inside the companion (why?) instead of being referenced as a sub-module.

**Comment by cristianraiber** [comment]
Seems to be actually ok, was checking the wrong repo.

**Comment by c0sm1n87** [comment]
This is part of epsilon -> https://github.com/puikinsh/shapely/tree/master/inc/shapely-documentation it should be removed.
