### ISSUE TITLE
Problems with menu at Ipad

### ISSUE THREAD

**Issue by Joan6419** [puikinsh/shapely#179]
L.S.
I use Shapely for my new created website for a short period (nice theme by the way!!) and put in online.
I’ve got some remarks from persons who use an iPAd for checking my side and they found out that in case of sub categories in the main menu, only the sub pages can be activated and the main page doesn’t.
Please can you help me out?
[link to my site](www.cortijoelalamo.eu)

Thanks in advanced and kind regards!
Joan

**Comment by dodiemccaffrey** [comment]
I have the same issue and subscribed to this post a while ago, so I was wondering if you are any closer to a solution.  On both smartphone and tablet the dropdown navbar links are not responding for those links which relate to parent pages. In the case of this site, this affects the Welcome, Destinations and Terms & Booking page. The problem usually resolves itself when I change to desktop view. . – the site is (https://guided-mountain-walks.com/)
Thanks

**Comment by c0sm1n87** [comment]
I'll close this issue and continue conversation here: #193
