### ISSUE TITLE
Add tooltips to all inputs / settings that are missing them

### ISSUE THREAD

**Issue by cristianraiber** [puikinsh/shapely#182]
Currently, the one that needs a good explanation is the "Blog template" settings field under Shapely Options -> Blog Settings -> Blog template. 

Please look for other inputs missing tool tips and add them with corresponding documentation.

**Comment by c0sm1n87** [comment]
controls still missing description, tooltips or too vague. e.g. Show title in top call out box, Text for footer callout button
