### ISSUE TITLE
Very blurry background image on mobile

### ISSUE THREAD

**Issue by AnaMaican** [puikinsh/shapely#187]
![image](https://cloud.githubusercontent.com/assets/23457094/26305861/f3be7054-3ee8-11e7-8e2c-cc89a6f3ff5d.png)

Reported by: Cristi

**Comment by giucu91** [comment]
@AnaMaican, @cristianraiber  if we use images with a larger height they will not be blurry anymore.

**Comment by c0sm1n87** [comment]
The image will be replaced in the demo files
