### ISSUE TITLE
Back to top now doesn't have smooth scroll to top effect. 

### ISSUE THREAD

**Issue by puikinsh** [puikinsh/shapely#19]
Latest update broke smooth back to top scroll effect.

**Comment by FreeWPTP** [comment]
Related Topic :

https://colorlib.com/wp/forums/topic/smooth-scroll-issue/#post-66804

**Comment by cristianraiber** [comment]
Back to top has been brought ... back? (pun intended). Marking as invalid as this has been probably fixed throughout the past updates.
