### ISSUE TITLE
Shapely Companion plugin breaks installation

### ISSUE THREAD

**Issue by ezekini** [puikinsh/shapely#190]
Hello. I think there ir is a bug with the Shapely Companion plugin. After installing it, if I activate it, the WP installation breaks. I get HTTP ERROR 500 and I can't access the site anymore. If I manually delete the plugin via FTP, the site comes alive again. I am on wordpress 4.7.5
![screen shot 2017-05-24 at 10 33 59](https://cloud.githubusercontent.com/assets/7750799/26405710/8b585e1e-406c-11e7-9bb6-7aa4ea159f8d.png)

**Comment by cristianraiber** [comment]
@ezekini - where did you download the Shapely Companion plugin from? WordPress.org or GitHub?

**Comment by Rychillie** [comment]
I was able to solve the problem by upgrading PHP to version 7

**Comment by cristianraiber** [comment]
Will be closing this as the minimum PHP version recommended by WordPress is actually 7.x. You can see more about this here: https://wordpress.org/about/requirements/
