### ISSUE TITLE
Before-after image slider

### ISSUE THREAD

**Issue by kseniya2kviz** [puikinsh/shapely#196]
Hi,
Is it possible to make compatible a plugin with before-after function? For example this one, or any other with a similar function. It is useful and needed greatly for users dealing with visual-related areas, arch viz, photography etc.
https://wordpress.org/plugins/before-after-image-slider-lite/
Thanks,
Kseniya

**Comment by cristianraiber** [comment]
@kseniya2kviz - this is something that could be very interesting to have support for in the theme. Can't say for sure when it'll be added, but we'll take it into consideration.

**Comment by cristianraiber** [comment]
@kseniya2kviz - Upon further thinking, I think that Shapely is already compatible with this plugin, you just didn't know it :) Using a regular "text" widget, or, as of WordPress 4.8.1 the HTML widget, you can place a shortcode there. As per the plugins' documentation, a shortcode that generates the before-after image, looks something like this: 

```
[image-comparator
    left="http://test.moewe.io/before-after-image-slider-lite/wp-content/uploads/sites/12/2015/03/cobra_blend_right1.jpg"
    left_alt="The cobra is red"
    right="http://test.moewe.io/before-after-image-slider-lite/wp-content/uploads/sites/12/2015/03/cobra_blend_left.jpg"
    right_alt="The cobra is black"
    width="70%" classes="hover"
    title="With hover (just move the mouse)"]
[/image-comparator]
```

To get this shortcode to work in your widget, just drop this line in your functions.php file: 

```
add_filter( 'widget_text', 'do_shortcode' );
```

**Comment by cristianraiber** [comment]
I am going to be marking this ticket as closed as the above should get you the achieved end result and it's not a theme feature request either.
