### ISSUE TITLE
Shapely Companion plugin generates notices when wp debug is on

### ISSUE THREAD

**Issue by vinoddalvi** [puikinsh/shapely#197]
The following notices are displayed when Shapely Companion plugin is activated and wp debug is on.

Notice: wp_enqueue_style was called incorrectly. Scripts and styles should not be registered or enqueued until the wp_enqueue_scripts, admin_enqueue_scripts, or login_enqueue_scripts hooks. Please see Debugging in WordPress for more information. (This message was added in version 3.3.0.) in /wp-includes/functions.php on line 4139

Notice: Array to string conversion in /wp-content/plugins/shapely-companion/inc/class-epsilon-framework.php on line 14

Notice: Array to string conversion in /wp-content/plugins/shapely-companion/inc/class-epsilon-framework.php on line 14

**Comment by cristianraiber** [comment]
@vinoddalvi - what PHP version ?

**Comment by vinoddalvi** [comment]
I am using PHP version 7.1.1 and could confirm latest Shapely Companion plugin update 1.0.6 fixed this issue so closing it.
