### ISSUE TITLE
missing \<\/div\> in blog archive page - sidebar in wrong place

### ISSUE THREAD

**Issue by leemd** [puikinsh/shapely#198]
In Shapely 1.1.6, there seems to be a missing \<\/div\> between the primary and secondary id sections.  This means that the sidebar is part of the col-md-8 div, and therefore never appears at the side where it should! 
See http://colorlib.com/shapely/blog/ for an example of this in action.
The missing \<\/div\> should probably be in the line before the one beginning \<aside id="secondary"... in the output html.

**Comment by cristianraiber** [comment]
@c0sm1n87 - please see this.

**Comment by cristianraiber** [comment]
![image](https://user-images.githubusercontent.com/7841556/28113929-4727ee78-6707-11e7-9830-5046cb1af592.png)
