### ISSUE TITLE
Add portfolio widget options

### ISSUE THREAD

**Issue by rhuanbarreto** [puikinsh/shapely#201]
You could add some options to the portfolio widget at the customizer:

- Define a background for it (Optional: add parallax)
- Define if the widget design is full size

The widget also have some design bug fixing:

- Maintain h1 on the header like the other widgets
- Maintain the same height for the featured images
- Share the image width (Like in Illdy)

**Comment by laranz** [comment]
When adding background and color in the Porfolio widget the colors didn't take effect. It takes effect only if we change something in the text blocks. Try it out by opening the Customizer.
