### ISSUE TITLE
White space above Contact Form Section

### ISSUE THREAD

**Issue by cristianraiber** [puikinsh/shapely#211]
White Space
---

![image](https://user-images.githubusercontent.com/7841556/28114634-4a844438-670a-11e7-91b0-fe07db7db669.png)

CF7 form errors
---
![image](https://user-images.githubusercontent.com/7841556/28114656-616ecac4-670a-11e7-858f-c4e4a2a3eb99.png)

**Comment by giucu91** [comment]
I can't reproduce the White space issue.
