### ISSUE TITLE
What should the page header display

### ISSUE THREAD

**Issue by simonschllng** [puikinsh/shapely#216]
For me the options "Blog Name in Top Callout (Heading for the Blog page)" has no effect and the header is empty despite the background image. What should be displayed here? The page Title?

**Comment by cristianraiber** [comment]
@giucu91 - please see this.

**Comment by simonschllng** [comment]
I went through the code and realized, that the responsible setting switch for `hide_post_title` is placed into `wpseo_breadcrumbs_customizer_section` in `inc/customizer.php:228`. This section was hidden by `wordpress-seo` plugin because it was not in advanced mode. Hard to find, should be easier.
