### ISSUE TITLE
Embedding a youtube video in a parallax section

### ISSUE THREAD

**Issue by a-support** [puikinsh/shapely#220]
It has been requested to allow users to embedding a youtube video in a parallax section.
https://colorlib.com/wp/forums/topic/embedding-youtube-video-in-parallax-page/#post-114411

**Comment by cristianraiber** [comment]
@a-support - are users expecting to create a parallax video background or just regular video in the background?

**Comment by a-support** [comment]
@cristianraiber The user want to embed a youtube video onto a parallax section.
