### ISSUE TITLE
Customizing header for Portfolio Single Post.

### ISSUE THREAD

**Issue by laranz** [puikinsh/shapely#221]
WE have an option to disable the header in the blog pages ( that also disable the title in portfolio pages )

![Alt text](https://monosnap.com/file/bmBEJDDLDh0vQCilKSqYEBMhr8WYnA.png)

But It is good if we have an option separately for portfolio pages, so that use can have that in blog pages and disable that in portfolio pages.

**Comment by cristianraiber** [comment]
@laranz - just to be sure we're clear on this. What you're asking is to add another toggle that changes "show title in header" for portfolio custom post types, right?

**Comment by laranz** [comment]
Yes, you can check in the screenshot.. If we don't have breadcrumbs, it took so much space in the header. So we can add a button just for portfolio to hide that. Hope this helps. :)
