### ISSUE TITLE
Portfolio Title Issue - When Yoast is Enabled.

### ISSUE THREAD

**Issue by laranz** [puikinsh/shapely#222]
1. When we enable the Yoast plugin, the portfolio single post page, the title looks like a blank,

![image](https://user-images.githubusercontent.com/208945/30041681-afe1f77e-9209-11e7-964e-063fc5b0e231.png)

2. To fix that, go to /wp-content/themes/shapely/inc/extras.php line number 584 you will see this line,

`$title_in_post       = get_theme_mod( 'hide_post_title', false );`

change that to,

`$title_in_post       = get_theme_mod( 'hide_post_title', true );`

Regards,

**Comment by laranz** [comment]
@giucu91 @cristianraiber any update on this? It also happens for the page that has top callout.

**Comment by cristianraiber** [comment]
@giucu91 - we need to take a look at this after we're done with Bonkers.
