### ISSUE TITLE
Portfolio Related Posts Shows "posts" not portfolio

### ISSUE THREAD

**Issue by laranz** [puikinsh/shapely#225]
If we turn on Appearance -> Customize -> Blog Settings -> Related Posts Area -> ON, In portfolio single page also it shows the related posts, and also it shows posts *not* portfolio..

We need to show the portfolio or we need to remove that from portfolio single post view.

**Comment by cristianraiber** [comment]
Yep, this makes sense. Ideally, the related posts "section" shouldn't show up on any other custom post type than `post`. Since it's showing up, we'll address this as well.
