### ISSUE TITLE
Parallax jumping on mobile.

### ISSUE THREAD

**Issue by laranz** [puikinsh/shapely#226]
I’m noticing a strange issue on a site I’ve built at fazeducation.com. On Chrome/Firefox in iOS, the background “jumps” or zooms upon scrolling. I have tried a few workarounds to no avail, and also see the same effect on the Shapely demo. Videos here for reference:

https://www.dropbox.com/s/6wmzsxcsgxp0pfy/shapely-demo.mov?dl=0
https://www.dropbox.com/s/lzs5py72ncbnig4/faz-education.mov?dl=0

https://colorlib.com/wp/forums/topic/parallax-image-jumping-effect-in-chromefirefox-ios/

Port from https://github.com/puikinsh/illdy/issues/225 as per @giucu91 's guide.

**Comment by hubyhuby** [comment]
I did the 1.2.0 update and on my android device with firefox and samsung internet explorer, I still have the jump when scrolling down.
I tried to refresh the page...maybe the JS cache.

**Comment by hubyhuby** [comment]
I have the same behaviour on Firefox android and firefox Linux with 1.2.0 and the previous version.
The background image zoom unzoom each time your scroll.
It seams like it might be related to the top menu aswell...

**Comment by cristianraiber** [comment]
@hubyhuby - our next theme update should address this issue. Please feel free to comment in this ticket and we'll reopen it if the next theme update doesn't address it for you.
