### ISSUE TITLE
Testimonial section does not auto scroll on mobile

### ISSUE THREAD

**Issue by laranz** [puikinsh/shapely#228]
The testimonial section auto scrolls perfectly on desktop BUT on mobile it stays stuck on the first testimonial. 

I tried in my iPad, also this isn't working.. Maybe this is the issue? https://github.com/woocommerce/FlexSlider/issues/938

Reported here: https://colorlib.com/wp/forums/topic/testimonial-section-does-not-auto-scroll-on-mobile/

Regards

**Comment by cristianraiber** [comment]
@laranz - thanks for reporting this.

We'll investigate and see. Your link looks like a good starting point - thank you for providing it :)

**Comment by cristianraiber** [comment]
@laranz - this should be addressed with our upcoming update. Please check and reply here if it's still happening at your end.
