### ISSUE TITLE
One Page links.

### ISSUE THREAD

**Issue by laranz** [puikinsh/shapely#229]
Hi @cristianraiber 

![image](https://user-images.githubusercontent.com/208945/31324586-cff3ab56-acd1-11e7-81dc-0e20c29b6a47.png)

Currently we can use the ID to use the one page links, it looks a bit ugly when we link like 

http://example.com/#shapely_home_parallax-3

So instead we can provide the user with the Custom ID, we may get that from the widget settings along with the title and other settings and give that ID to the section like this,

![image](https://user-images.githubusercontent.com/208945/31324618-196c99b4-acd2-11e7-88de-c33661bdbed0.png)

So the one page URL has a meaning, http://example.com/#who_we_are

Hope I wrote it clear. :)

**Comment by cristianraiber** [comment]
@laranz - Yep, I understand the feature request. I do have a question though: where do the users want to use this? In the site's nav menu?

**Comment by laranz** [comment]
Hi,

Yes in the Site Nav link or anywhere, if we change the ID he can link that anywhere right? Also, as a one page website, we need to add the smooth scroll, that would be helpful. :)

**Comment by cristianraiber** [comment]
@laranz - it's important for us to understand where users expect to see/use this feature. It wouldn't be user friendly to throw it in all the theme's panels just to have it there. What I'm trying to find out here is where exactly have users tried to use this functionality? What are they trying to achieve? 

Yes, we will also add smooth scroll.

**Comment by laranz** [comment]
@cristianraiber not in the theme's panel, some other better way. Some users feels that the link is appropirate..

For example, one particular section is about testimonial, and we link to that section in the menu, like this, http://example.com/#home_shapely_testimonial_3.. instead that meaningless URL, what if we give like this, http://example.com/#testimonial so that user can understand it when it appears in the browser address bar.. Hope I understand better. :)

Something like: https://colorlib.com/wp/forums/topic/how-to-rename-anchor-sections/#post-126188

Regards,

**Comment by cristianraiber** [comment]
@laranz - yup, this is what I had in mind as well. Just wanted to make sure I understood exactly what users are expecting from this.

@giucu91 - we need to add an extra field in the menu build process

**Comment by laranz** [comment]
@cristianraiber great :)

Not in the menu build process, we want that in the widget area isn't it.. when adding a widget we want to add a particular ID, so that we can use that for one page links.

Regards,

**Comment by cristianraiber** [comment]
@laranz - Instead of adding a manual ID, how about if we allow the users to select, in the menu build process, if they want to select to link to a certain page from a drop-down and our code does the rest? Users will never have to manually link to sections :)

**Comment by laranz** [comment]
Anything which is good. 👍 ask me to test once this feature is added. 👍

**Comment by cristianraiber** [comment]
@laranz - this is implemented currently only in the Appearance -> Menus. @giucu91  will be working on adding this inside the Customizer as well

**Comment by laranz** [comment]
@cristianraiber and @giucu91 Can we do the same for illdy and the future one-page themes? Is this possible? It makes easy for the users to create menu links for one page, especially one page theme like illdy. 👍

**Comment by cristianraiber** [comment]
@laranz - for future themes, you betcha. For Illdy, I'm not 100% sure it's doable, but we'll see.

**Comment by NextBlaubeere** [comment]
How is it possible, to change the IDs to custom ones?

**Comment by eumanobranco** [comment]
Sup @cristianraiber and @laranz ! i'mfacing another issue: I'm using shapely for a client and I came across the following situation: I need to put the div IDs in the learn more buttons, so that the page scrolls to the div where it has more information about that specific item. The problem is similar to that of lawrence, it appears in the url like this: https://aquinomorandi.com/agileerp/#shapely_home_parallax-3 (note that I am developing in real time on a subdomain of mine). Would it be possible for the code to hide the "shapely_home_parallax- 3"?
I think it looks ugly and confusing for the user who uses my client's page.
