### ISSUE TITLE
[Enchancement] Show mobile menu always.

### ISSUE THREAD

**Issue by laranz** [puikinsh/shapely#230]
Few users request that they want to show the mobile menu even in desktop like hide the actual menu and just want to show the hamburger icon and want to act the menu like it works on mobile. is that possible?

**Comment by cristianraiber** [comment]
@laranz - yes, that's possible :) Will be added to next theme update.

**Comment by giucu91** [comment]
Hello @laranz ,

Can  you please get the latest version of Shapely and Shapely Companion and then check all the issues reported by you ?

Have a nice day,
George.
