### ISSUE TITLE
[Enchancement] Add a option to choose category for Portfolio widget

### ISSUE THREAD

**Issue by laranz** [puikinsh/shapely#232]
Add a option to choose category for Portfolio widget also include all option so that it pulls all portfolio posts.

**Comment by giucu91** [comment]
Hello @laranz ,

What do you mean by all options ?

Thank you,
George.
Hello @laranz ,

What you mean by all option ?

Thank you,
George.

**Comment by laranz** [comment]
Hi,

Something like this,

![image](https://user-images.githubusercontent.com/208945/32390269-bebed212-c0f3-11e7-9b56-358c3a0095e8.png)

It has "All" in the top along with the other portfolio categories. Hope this helps.
