### ISSUE TITLE
[Bug] Portfolio widget homepage Masonry layout images are blurry.

### ISSUE THREAD

**Issue by laranz** [puikinsh/shapely#234]
Few users report this, after the update portfolio images in the home page are blurry. It seems Masonry view took the "Medium" size featured image and that is the cause of the issue? Anyway to fix it?

Reported here: https://colorlib.com/wp/forums/topic/pictures-with-bad-quality-when-using-masonry-layout/#post-129985

Regards,
@laranz

**Comment by cristianraiber** [comment]
@giucu91 - please look into this
