### ISSUE TITLE
Text overlapping checkbox on WooCommerce checkout page 

### ISSUE THREAD

**Issue by puikinsh** [puikinsh/shapely#235]
Text overapping chekbox on WooCommerce checkout page. Both on desktop and mobile. 

To replicate. Just add any products to your Cart and proceed to Checkout page.

<img width="479" alt="screenshot 2017-11-02 08 27 04" src="https://user-images.githubusercontent.com/3451398/32312685-c6320db8-bfa7-11e7-8415-115fa43c25f7.png">

**Comment by cristianraiber** [comment]
@giucu91 - please see this
