### ISSUE TITLE
Section not centered when set to RIGHT /Shapey Paralax

### ISSUE THREAD

**Issue by hubyhuby** [puikinsh/shapely#239]
When "image position" is set to RIGHT I get the WALL section (text + image) shifted on the LEFT (ie not centered).

When set to LEFT the complet section is always centered, which workes nicely.

Note that when I remove custom Css it does the same. Using shapely 1.2

I wish to use this right alignement specially to get the texte first in mobile view

**Comment by giucu91** [comment]
Hello @hubyhuby ,

Can you please describe a bit more the problem with the image's position ? 

From what I see on our demo ( https://colorlib.com/shapely/ ) the title & text are aligned to the left on both left & right positions.

**Comment by hubyhuby** [comment]
Hi @giucu91 ,
Just tried it again and removed even my custom css I get the same.
When I go to the demo it is perfectly center you are right : D

Might be because I use it just after the main paralax???

![shift](https://user-images.githubusercontent.com/26340942/34206321-59d1b524-e586-11e7-8104-85f6ec2d9de6.png)

**Comment by giucu91** [comment]
Hello,

Can you please give me your website's URL ?

Thank you,
George.

**Comment by hubyhuby** [comment]
tooap.com

**Comment by giucu91** [comment]
Thank you,

I found the problem. On our demo the image is bigger and this is why the image is centered. Thank you again for reporting this. I'll fix it.

Have a nice day,
George.

**Comment by hubyhuby** [comment]
Dear @giucu91 George,
Thanks a lot to you!!! You are doing a wonderfull job for this community.
This theme is working very nicely, saves soooo much time in getting  things done.

Have a nice christmas!
