### ISSUE TITLE
The widget icons having (alias) does not display in the front end

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/shapely#24]
Related Topic and Solution :

https://colorlib.com/wp/forums/topic/shapely-feature-widget-fa-legal-alias-not-working/

**Comment by cristianraiber** [comment]
@FreeWPTP - what's the fix here? I see you've given the fix to a client via a child theme.

**Comment by c0sm1n87** [comment]
as far as I can see, fa-legal icon si being displayed properly

**Comment by cristianraiber** [comment]
@FreeWPTP - can you help us here, please?

**Comment by FreeWPTP** [comment]
It's the issue of [Shapely] Features Section For FrontPage widget. When you select the icon in this widget option having word alias then it doesn't display as shown in the below screenshots so i have removed the alias word in the shared child theme.

![screenshot 6](https://cloud.githubusercontent.com/assets/11946142/21140497/58d0ebba-c15e-11e6-9c97-698785fad154.png)

![screenshot 4](https://cloud.githubusercontent.com/assets/11946142/21140500/5de51518-c15e-11e6-9a38-e9668cafda47.png)

![screenshot 5](https://cloud.githubusercontent.com/assets/11946142/21140508/6431b30e-c15e-11e6-978f-a016ecc574d8.png)

I don't see it in the updated github theme version but it was in the old theme version in the file widget-home-features.php when i reported it.

Please advise if you have more questions.

**Comment by cristianraiber** [comment]
@FreeWPTP - so we can close this, right?

**Comment by FreeWPTP** [comment]
Yes it is fixed in https://github.com/puikinsh/shapely-companion/commit/f4291a04e916bc6c60d4deb9c6b1d912792dda91
