### ISSUE TITLE
Plugin Incompatibility: Appointments by WPMUDEV

### ISSUE THREAD

**Issue by a-support** [puikinsh/shapely#241]
The Shapely theme appears to be incompatible with the [Appointments plugin](https://premium.wpmudev.org/project/appointments-plus/) from WPMU DEV. I would really like to use both this theme and the plugin together.

When trying to select an appointment slot, it works fine on the landing URL but as soon as any interactions occur, causing a query to be added to the URL it is not possible to click on any time slots.

When I use a default WordPress theme the plugin works fine.

**Comment by cristianraiber** [comment]
There's no way for us to test compatibility with that plugin as that's one paid one. If the WPMUDEV or the client can provide a copy of the plugin, we can handle it. Since this is a single request, I'm going to close this ticket and mark it as `wontfix`.
