### ISSUE TITLE
Video Widget Issue: Video Upload Controls Options not working

### ISSUE THREAD

**Issue by a-support** [puikinsh/shapely#242]
When using the Video widget, the user is unable to upload video using video upload controls.
Placeholder image does not work either. Youtube works fine. 

Discussion: https://colorlib.com/wp/forums/topic/shapely-video-section/

**Comment by cristianraiber** [comment]
@giucu91 - we need to look into this

**Comment by cristianraiber** [comment]
@a-support -this has been addressed in our upcoming theme release. Please check and report here if you find any problems
