### ISSUE TITLE
Structured data: entry-title & author hentry missing fields

### ISSUE THREAD

**Issue by hubyhuby** [puikinsh/shapely#243]
After scanning my website google detects errors in the structured data at https://www.google.com/webmasters/tools/structured-data
It informs that all my posts and pages are missing the following hentry AND hatom fields : 
* entry-title 
* author

As per the google analysis other fields seems correct, as per the picture : 
![bug_hentry_structureddata](https://user-images.githubusercontent.com/26340942/35182919-733c65c6-fddd-11e7-91ee-ba1b891aa660.jpg)

**Comment by cristianraiber** [comment]
@hubyhuby - thanks for reporting this :) I've added it to the next theme update.

**Comment by cristianraiber** [comment]
@hubyhuby - could you please help me out with your site's URL? I've tried reproducing this error on a test site (http://usatopservices.com/blog/ && http://usatopservices.com/2018/04/23/hello-world/) but to no avail.  Google's Structured Data tool doesn't return any errors for me. 

Could you also please let me know the full list of plugins you're using?

**Comment by hubyhuby** [comment]
Dear @cristianraiber ,
My website is using ShapelyVersion : 1.2
It can be found on google by typing tooap
Thanks a lot for your help

**Comment by hubyhuby** [comment]
Dear @cristianraiber ,
Sorry for the late reply.
I am not experiencing errors in the "data structure" but in the google console tool crawler.
Google crawler tells me it is an error to not have  " entry-title" and  "author" defined in my pages.

Thank you for your help


`AddToAny Share ButtonsRéglages \| Désactiver \| Modifier | Share buttons for your pages  including AddToAny's universal sharing button, Facebook, Twitter,  Google+, Pinterest, WhatsApp and many more. 						Version 1.7.23 \| Par AddToAny \| Afficher les détails
-- | --
Une nouvelle version pour AddToAny Share Buttons est disponible. Afficher les détails de la version 1.7.25 ou mettre à jour maintenant.
Akismet Anti-SpamActiver \| Modifier \| Supprimer | Used by millions, Akismet is quite possibly the best way in the world to protect your blog from spam.  It keeps your site protected even while you sleep. To get started:  activate the Akismet plugin and then go to your Akismet Settings page to  set up your API key. 						Version 3.3.4 \| Par Automattic \| Afficher les détails
Une nouvelle version pour Akismet Anti-Spam est disponible. Afficher les détails de la version 4.0.3 ou mettre à jour maintenant.
amr shortcode any widgetDésactiver \| Modifier \| Where using? \| HELP | Include any widget in a page  for any theme.  [do_widget widgetname ] or  [do_widget "widget name" ]  [do_widget id=widgetnamedashed-n ]or include a whole widget area  [do_widget_area]. Please see FAQ. 						Version 3.6 \| Par anmari \| Afficher les détails
Display Posts ShortcodeActiver \| Modifier \| Supprimer | Display a listing of posts using the [display-posts] shortcode 						Version 2.9.0 \| Par Bill Erickson \| Afficher les détails
Easy Smooth Scroll LinksSettings \| Désactiver \| Modifier | ESSL Wordpress plugin adds interesting scroll animation effects to page anchors, smooth scroll and more. 						Version 2.1.1 \| Par pandasilk \| Afficher les détails
GeoIP DetectionDésactiver \| Modifier \| Lookup \| Options | Retrieving Geo-Information using the Maxmind GeoIP (Lite) Database. 						Version 2.8.2 \| Par Yellow Tree (Benjamin Pick) \| Afficher les détails
Hello DollyActiver \| Modifier \| Supprimer | Ce n’est pas qu’une extension.  Elle symbolise l’espoir et l’enthousiasme de toute une génération,  résumé en deux mots, qu’a notamment chanté Louis Armstrong : Hello,  Dolly. Une fois activée, elle affichera une ligne aléatoirement des  paroles de la chanson Hello, Dolly, en haut à droite de toutes les pages  de l’administration. 						Version 1.6 \| Par Matt Mullenweg \| Afficher les détails
Image de profil utilisateurDésactiver \| Modifier | Utiliser l’envoi natif de WP sur vos page de profil utilisateur 						Version 1.4.3 \| Par Ronald Huereca \| Afficher les détails
Jetpack par WordPress.comJetpack \| Désactiver \| Modifier | Ajoutez la puissance du cloud  de WordPress.com à votre site WordPress auto-hébergé. Jetpack vous  permet de connecter votre blog à un compte WordPress.com pour profiter  de fonctionnalités normalement réservées aux utilisateurs de  WordPress.com. 						Version 5.4 \| Par Automattic \| Afficher les détails
Une nouvelle version pour Jetpack par WordPress.com est disponible. Afficher les détails de la version 6.0 ou mettre à jour maintenant.
PolylangRéglages \| Désactiver \| Modifier | Permet une utilisation multilingue de WordPress 						Version 2.2.4 \| Par Frédéric Demarle \| Afficher les détails
Une nouvelle version pour Polylang est disponible. Afficher les détails de la version 2.3.4 ou mettre à jour maintenant.
Remove Category URLActiver \| Modifier \| Supprimer | This plugin removes '/category' from your category permalinks. (e.g. `/category/my-category/` to `/my-category/`) 						Version 1.1.2 \| Par Valerio Souza \| Afficher les détails
Shapely CompanionDésactiver \| Modifier | Shapely Companion is a companion plugin for Shapely theme. 						Version 1.2.0 \| Par Colorlib \| Afficher les détails
Une nouvelle version pour Shapely Companion est disponible. Afficher les détails de la version 1.2.1 ou mettre à jour maintenant.
Shortcode WidgetActiver \| Modifier \| Supprimer | Adds a text-like widget that allows you to write shortcode in it. (Just whats missing in the default text widget) 						Version 1.5.1 \| Par Gagan Deep Singh \| Afficher les détails
Simply StaticDésactiver \| Modifier | Produit une version HTML statique de votre installation WordPress et ajuste les URLs en conséquence. 						Version 2.1.0 \| Par Code of Conduct LLC \| Afficher les détails
Smooth Scroll Page Up/Down ButtonsActiver \| Modifier \| Supprimer | Adds buttons to your page that will enable the user to easily (and smoothly) scroll one screen up/down. 						Version 1.3 \| Par Mark Senff \| Afficher les détails
Widget Importer & ExporterDésactiver \| Modifier \| Import/Export | Importez et exportez vos widgets. 						Version 1.5.2 \| Par WP Ultimate \| Afficher les détails
Une nouvelle version pour Widget Importer & Exporter est disponible. Afficher les détails de la version 1.5.3 ou mettre à jour maintenant.
WordPress ImporterDésactiver \| Modifier | Importez les articles, pages,  commentaires, champs personnalisés, catégories, étiquettes et plus à  partir d'un fichier d’export de WordPress. 						Version 0.6.3 \| Par wordpressdotorg \| Afficher les détails
Une nouvelle version pour WordPress Importer est disponible. Afficher les détails de la version 0.6.4 ou mettre à jour maintenant.
WPBakery Page Builder(Paramètres) \| Désactiver \| Modifier | Drag and drop page builder for  WordPress. Take full control over your WordPress site, build any layout  you can imagine – no programming knowledge required. 						Version 5.4.5 \| Par Michael M - WPBakery.com \| Afficher les détails
Une nouvelle version pour WPBakery Page Builder est disponible. Afficher les détails de la version 5.4.7. La mise à jour automatique n’est pas disponible pour cette extension. To receive automatic updates license activation is required. Please visit settings to activate your WPBakery Page Builder. Got WPBakery Page Builder in theme?
Yoast SEOFAQ \| Support Premium \| Réglages \| Désactiver \| Modifier | La première solution SEO  tout-en-un pour WordPress, y compris l’analyse des pages de contenu, les  sitemaps XML et bien plus encore. 						Version 5.7.1 \| Par L’équipe Yoast \| Afficher les détails
Une nouvelle version pour Yoast SEO est disponible. Afficher les détails de la version 7.3 ou mettre à jour maintenant.


AddToAny Share ButtonsRéglages \| Désactiver \| Modifier | Share buttons for your pages  including AddToAny's universal sharing button, Facebook, Twitter,  Google+, Pinterest, WhatsApp and many more. 						Version 1.7.23 \| Par AddToAny \| Afficher les détails
-- | --
Une nouvelle version pour AddToAny Share Buttons est disponible. Afficher les détails de la version 1.7.25 ou mettre à jour maintenant.
amr shortcode any widgetDésactiver \| Modifier \| Where using? \| HELP | Include any widget in a page  for any theme.  [do_widget widgetname ] or  [do_widget "widget name" ]  [do_widget id=widgetnamedashed-n ]or include a whole widget area  [do_widget_area]. Please see FAQ. 						Version 3.6 \| Par anmari \| Afficher les détails
Easy Smooth Scroll LinksSettings \| Désactiver \| Modifier | ESSL Wordpress plugin adds interesting scroll animation effects to page anchors, smooth scroll and more. 						Version 2.1.1 \| Par pandasilk \| Afficher les détails
GeoIP DetectionDésactiver \| Modifier \| Lookup \| Options | Retrieving Geo-Information using the Maxmind GeoIP (Lite) Database. 						Version 2.8.2 \| Par Yellow Tree (Benjamin Pick) \| Afficher les détails
Image de profil utilisateurDésactiver \| Modifier | Utiliser l’envoi natif de WP sur vos page de profil utilisateur 						Version 1.4.3 \| Par Ronald Huereca \| Afficher les détails
Jetpack par WordPress.comJetpack \| Désactiver \| Modifier | Ajoutez la puissance du cloud  de WordPress.com à votre site WordPress auto-hébergé. Jetpack vous  permet de connecter votre blog à un compte WordPress.com pour profiter  de fonctionnalités normalement réservées aux utilisateurs de  WordPress.com. 						Version 5.4 \| Par Automattic \| Afficher les détails
Une nouvelle version pour Jetpack par WordPress.com est disponible. Afficher les détails de la version 6.0 ou mettre à jour maintenant.
PolylangRéglages \| Désactiver \| Modifier | Permet une utilisation multilingue de WordPress 						Version 2.2.4 \| Par Frédéric Demarle \| Afficher les détails
Une nouvelle version pour Polylang est disponible. Afficher les détails de la version 2.3.4 ou mettre à jour maintenant.
Shapely CompanionDésactiver \| Modifier | Shapely Companion is a companion plugin for Shapely theme. 						Version 1.2.0 \| Par Colorlib \| Afficher les détails
Une nouvelle version pour Shapely Companion est disponible. Afficher les détails de la version 1.2.1 ou mettre à jour maintenant.
Simply StaticDésactiver \| Modifier | Produit une version HTML statique de votre installation WordPress et ajuste les URLs en conséquence. 						Version 2.1.0 \| Par Code of Conduct LLC \| Afficher les détails
Widget Importer & ExporterDésactiver \| Modifier \| Import/Export | Importez et exportez vos widgets. 						Version 1.5.2 \| Par WP Ultimate \| Afficher les détails
Une nouvelle version pour Widget Importer & Exporter est disponible. Afficher les détails de la version 1.5.3 ou mettre à jour maintenant.
WordPress ImporterDésactiver \| Modifier | Importez les articles, pages,  commentaires, champs personnalisés, catégories, étiquettes et plus à  partir d'un fichier d’export de WordPress. 						Version 0.6.3 \| Par wordpressdotorg \| Afficher les détails
Une nouvelle version pour WordPress Importer est disponible. Afficher les détails de la version 0.6.4 ou mettre à jour maintenant.
WPBakery Page Builder(Paramètres) \| Désactiver \| Modifier | Drag and drop page builder for  WordPress. Take full control over your WordPress site, build any layout  you can imagine – no programming knowledge required. 						Version 5.4.5 \| Par Michael M - WPBakery.com \| Afficher les détails
Une nouvelle version pour WPBakery Page Builder est disponible. Afficher les détails de la version 5.4.7. La mise à jour automatique n’est pas disponible pour cette extension. To receive automatic updates license activation is required. Please visit settings to activate your WPBakery Page Builder. Got WPBakery Page Builder in theme?
Yoast SEOFAQ \| Support Premium \| Réglages \| Désactiver \| Modifier | La première solution SEO  tout-en-un pour WordPress, y compris l’analyse des pages de contenu, les  sitemaps XML et bien plus encore. 						Version 5.7.1 \| Par L’équipe Yoast \| Afficher les détails
Une nouvelle version pour Yoast SEO est disponible. Afficher les détails de la version 7.3 ou mettre à jour maintenant.

`

**Comment by hubyhuby** [comment]
*Recommended by google for an article here:
https://developers.google.com/search/docs/data-types/article
It is clear that Author is the first needed element.
"
author | Person or Organization, **required**       The author of the article.
-- | --
author.name | Text, **required**       The name of the author.
"

*What we get with Shapely is not a proper definition of an article :
https://search.google.com/structured-data/testing-tool/u/0/#url=http%3A%2F%2Ftooap.com%2Fblog%2Fameliorez-votre-page-facebook-partie-2%2F

**Comment by hubyhuby** [comment]
Dear @cristianraiber ,
Did you manage to solve the issue ?
This would be great .
Have a nice week end

**Comment by cristianraiber** [comment]
@hubyhuby - I have not managed to reproduce this at my end, unfortunately.
