### ISSUE TITLE
Duplicate type="text" in shapely_search_form

### ISSUE THREAD

**Issue by Jozze** [puikinsh/shapely#245]
The shapely_search_form inside /inc/extras.php contains an error. 

`<input type="text" placeholder="' . esc_html__( 'Type Here', 'shapely' ) . '" type="text" value="' . esc_attr( get_search_query() ) . '" name="s" id="s" />`

`type="text"` is used twice. This is not valid and should be changed.

**Comment by cristianraiber** [comment]
@Jozze - a pull request with this fix would be awesome :)

**Comment by Jozze** [comment]
@cristianraiber Suprisingly never done it before ^^, but sure. I created a pull request.

**Comment by cristianraiber** [comment]
@Jozze - thanks for your pull request :) 

Marking as closed, since it was fixed here: https://github.com/puikinsh/shapely/pull/246#pullrequestreview-91306310
