### ISSUE TITLE
WooCommerce template files must be updated to the latest version

### ISSUE THREAD

**Issue by puikinsh** [puikinsh/shapely#247]
More and more users have started to complain about this: 

<img width="1171" alt="screenshot 2018-02-07 17 01 11" src="https://user-images.githubusercontent.com/3451398/35923384-c228637a-0c28-11e8-90a8-50c97383ad56.png">

Must be fixed.

**Comment by cristianraiber** [comment]
@giucu91 - let's include this in the update of Shapely that we've been working on
