### ISSUE TITLE
Plugin blocks parallax image.

### ISSUE THREAD

**Issue by a-support** [puikinsh/shapely#251]
The Enhanced E-commerce for Woocommerce store plugin is preventing the parallax image from being displayed.

Reference:
https://colorlib.com/wp/forums/topic/theme-only-appears-properly-when-logged-in-as-admin/#post-147783

**Comment by cristianraiber** [comment]
@a-support - I am unable to reproduce this error. I've tried with latest Enhanced Ecommerce plugin version and latest Shapely.
