### ISSUE TITLE
Product Review Section Style issue

### ISSUE THREAD

**Issue by laranz** [puikinsh/shapely#253]
Please check the review tab for the product ( Make sure you're not logged in ) https://colorlib.com/shapely/product/woo-logo/

![image](https://user-images.githubusercontent.com/208945/37262968-f7fead30-25cb-11e8-9192-9fda7e9395a3.png)

**Comment by cristianraiber** [comment]
@giucu91 - we need to address this

**Comment by cristianraiber** [comment]
![image](https://user-images.githubusercontent.com/7841556/39264135-cc35fa0e-48cc-11e8-8f79-2849acaf272c.png)

**Comment by cristianraiber** [comment]
![image](https://user-images.githubusercontent.com/7841556/39264147-d45c0a70-48cc-11e8-8e4a-abff24721988.png)
