### ISSUE TITLE
Video section on frontpage with big black gaps

### ISSUE THREAD

**Issue by laranz** [puikinsh/shapely#256]
When we using a Video it creates styling issue,  like this illdy issue, https://github.com/puikinsh/illdy/issues/263

Reported here: https://colorlib.com/wp/forums/topic/video-section-on-frontpage-with-big-black-gaps/

Regards,

**Comment by cristianraiber** [comment]
@laranz - this is not an actual bug, but rather an issue with the video size (ratio).
