### ISSUE TITLE
Background full & small images in parralex section not working on "Builder Page"

### ISSUE THREAD

**Issue by laranz** [puikinsh/shapely#257]
Hi,

We recently launch this "Builder Page" feature, and it works very well, but when we add a Parallax widget into it, the background full and small image mode is not working. Please take a look,

Reported here: https://colorlib.com/wp/forums/topic/background-full-small-images-in-parralex-section-not-working-on-new-template/

Regards,

**Comment by cristianraiber** [comment]
@laranz - I can confirm this is indeed an issue and it's coming from this line: 

https://github.com/puikinsh/shapely/blob/master/functions.php#L250

For people who want to get this working, until we release an update, just have them remove the IF statement on that line.
