### ISSUE TITLE
Homepage widgets option doesn't display in the customizer widgets section

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/shapely#26]
Related Topic :

https://colorlib.com/wp/forums/topic/homepage-missing-wiget-option/#post-62754

**Comment by puikinsh** [comment]
It does display when homepage (Page) template is actually being used.

**Comment by FreeWPTP** [comment]
Tested it on my test site and confirmed it's displaying when the  homepage (Page) template is actually being used and that page is set as static Front page.
