### ISSUE TITLE
Parallax Images not responsive

### ISSUE THREAD

**Issue by laranz** [puikinsh/shapely#260]
Reported here: https://colorlib.com/wp/forums/topic/images-not-responsive-on-mobile/

**Comment by cristianraiber** [comment]
@laranz - I've followed the thread and read her ticket, but I'm not quite sure I understand the problem. 

In the screenshot she's attached, the images seem fine to me. Am I missing something?

**Comment by laranz** [comment]
@cristianraiber The parallax images ( background images ) by default won't resize according to the screen width. If there is a solution to that, it would be wonderful. :) You can check the same in your localhost, insert an image as a parallax image with so many people standing, and then check in mobile width,only few people are showing. 

Hope I explained better.

**Comment by cristianraiber** [comment]
![image](https://user-images.githubusercontent.com/7841556/39263019-bc19859e-48c9-11e8-80e7-05d328fe0df6.png)

**Comment by cristianraiber** [comment]
![image](https://user-images.githubusercontent.com/7841556/39263043-c69b07f4-48c9-11e8-96bc-aebcde02e1e1.png)

**Comment by cristianraiber** [comment]
@laranz - I'm not able to reproduce your issue. The image with a lot of people is displaying properly on iPhone / iPads. What device did you use to test this?
