### ISSUE TITLE
Third level drop down menu does not work on mobile devices

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/shapely#27]
Related Topic :

https://colorlib.com/wp/forums/topic/dropdown-menu-3rd-level/

**Comment by cristianraiber** [comment]
@FreeWPTP - While the provided solution does seem to work on desktop browsers, I've tested it with an iPhone and it doesn't work. 

Solution provided by @FreeWPTP 

```
@media (max-width: 991px){
.menu ul.dropdown-menu li a {
    width: 90%;
}
.main-navigation ul ul li:hover > ul, .main-navigation ul ul li.focus > ul{
  left: 0;
  position: relative;
}
}```

---

@c0sm1n87 - let's fix this as well.

**Comment by cristianraiber** [comment]
This seems to have been fixed.
