### ISSUE TITLE
[Shapely] Client Section For FrontPage widget doesn't work in theme customizer

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/shapely#28]
The [Shapely] Client Section For FrontPage widget buttons don't work in theme customizer Admin area ->  Appearance -> Customize

Related Topic :
https://colorlib.com/wp/forums/topic/client-section-not-working/

**Comment by Cojomax99** [comment]
+1 - confirmed issue

**Comment by cristianraiber** [comment]
Fixed. Works fine now.
