### ISSUE TITLE
Parse error: syntax error, unexpected ‘[‘ 

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/shapely#35]
Related topic and solution :

https://colorlib.com/wp/forums/topic/error-500-when-install/

**Comment by cristianraiber** [comment]
@c0sm1n87 - this seems like invalid to me, but please investigate just to make sure.

**Comment by c0sm1n87** [comment]
invalid, there are no widgets in the current version of the template.

Parse error: syntax error, unexpected ‘[‘ in /home/f/frontyacom/saucony/public_html/wp-content/themes/shapely-master/**inc/widgets/widget-home-clients.php** on line 65

**Comment by cristianraiber** [comment]
Closing as this one's invalid.
