### ISSUE TITLE
Error after activating

### ISSUE THREAD

**Issue by bomboleilo** [puikinsh/shapely#37]
Hi, i have a problem after activating the theme. White blank in live preview and broken web site after activating theme. On localhost everything works great, but not on the hosted website

**Comment by FreeWPTP** [comment]
Please post your question on our following shapely theme support forum so that we can help you to resolve this issue.

https://colorlib.com/wp/forums/forum/shapely/

**Comment by cristianraiber** [comment]
Most likely a PHP issue. Shared hosting accounts using PHP < 5.6 (the WP minimum recommended) tend to behave like this. Marking as invalid & closing as it's only one person reporting this behaviour.
