### ISSUE TITLE
Report from email

### ISSUE THREAD

**Issue by puikinsh** [puikinsh/shapely#44]
I am currently using your theme Shapely Version: 1.0.5 on Wordpress 4.6 (Mozilla Firefox 48.0 - Linux Mint 17.3 Rosa) and I have stumbled upon an issue with your ' shapely_footer_callout() ' function in extras.php.

I could not display anything on my page through ' Text for footer callout ' neither ' Text for footer callout button ' input options in Customizer/Shapely Options/ Main Options with these lines of code in place from above mentioned function:

```
<?php esc_attr(get_theme_mod('footer_callout_text')); ?>
<?php esc_attr(get_theme_mod('footer_callout_btntext')); ?>
```

so I changed them into:

```
<?php esc_attr_e( ( get_theme_mod('footer_callout_text') ) ? get_theme_mod('footer_callout_text') : 'Text' , 'shapely' ); ?>
```

```
<?php esc_attr_e( ( get_theme_mod('footer_callout_btntext') ) ? get_theme_mod('footer_callout_btntext') : 'ButtonText' , 'shapely' ); ?>
```

**Comment by cristianraiber** [comment]
This seems to have been fixed. SS from my local testing machine.

![image](https://cloud.githubusercontent.com/assets/7841556/21044398/6e11ed1a-be04-11e6-90ff-733d1922d09c.png)

**Comment by cristianraiber** [comment]
Fixed here: https://github.com/puikinsh/shapely/blob/master/inc/extras.php#L581-L605
