### ISSUE TITLE
 Parralax section : Background full & small not working in the customization section in the admin area

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/shapely#45]
This is happening because of javascript error message occurred on the customization screen as shown in the shared screenshot.

Related topic :

https://colorlib.com/wp/forums/topic/parralux-section-background-full-small-not-working/

![screenshot](https://cloud.githubusercontent.com/assets/11946142/18837944/47dc1c3a-8423-11e6-958e-136e3c09d956.png)

**Comment by cristianraiber** [comment]
@c0sm1n87 - currently all `section` elements have a border-bottom. Some shouldn't have it or at least it should be behind a toggle. Maybe users don't want it? See below screenshot. Let's find a better approach. 

![image](https://cloud.githubusercontent.com/assets/7841556/21044888/b9c74cc6-be06-11e6-8dc2-096d64c10ae5.png)

**Comment by cristianraiber** [comment]
Border bottom is now toggled by a control inside the widget. Users decide if they want a border-bottom or not.
