### ISSUE TITLE
Feature Request - Make nav bar transition smooth from static to fixed and vice versa

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/shapely#46]
Related Topic :

https://colorlib.com/wp/forums/topic/fixed-scrolling-navigation/

https://colorlib.com/wp/forums/topic/animation-since-v1-0-5/#post-72558

**Comment by cristianraiber** [comment]
@c0sm1n87 - could you please investigate this? I've checked in Chrome Version 55.0.2883.75 (64-bit) on Mac OS and the transition seems pretty smooth to me.

**Comment by cristianraiber** [comment]
An effect has been implemented here. @c0sm1n87 - I think we should tweak the transition times a little on this. If I scroll fast enough, I get to to see the navbar disappearing and transitioning back into it's sticky/fixed position.

**Comment by cristianraiber** [comment]
This has been implemented.
