### ISSUE TITLE
The widgets are overlapping on other widgets

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/shapely#49]
Related Topic :

https://colorlib.com/wp/forums/topic/issue-with-parallax-in-homepage/

**Comment by Christin10-10m** [comment]
Any update on this? I love the theme but this issue is really noticeable and I only want to use this theme if the it can be resolved.

**Comment by cristianraiber** [comment]
@c0sm1n87 - please investigate.

**Comment by cristianraiber** [comment]
Couldn't reproduce at my end. Parallax sections work just fine in all the following browsers I've tested: Chrome, Firefox & Safari. Running Mac OS - 10.11.1 & latest version browsers.

**Comment by FreeWPTP** [comment]
@cristianraiber There are many users using this theme on the site and having this issue. Could you please share me your site URL so that i can test it?

**Comment by cristianraiber** [comment]
@FreeWPTP - we've only tested locally but I see no reason why tests should be different. Could you please share some client URLs where this was happening, since there were many who had this issue?

**Comment by FreeWPTP** [comment]
You won't see this issue locally as images load fast locally and you have to also set BG images large in size to reproduce the issue.

Here are some of the websites who reported the issue.
http://www.jardineriacalonge.com/
http://www.edenparkpanelpaint.co.nz/

**Comment by cristianraiber** [comment]
@c0sm1n87 - can you please investigate?

**Comment by c0sm1n87** [comment]
please test this with the latest version of the theme

**Comment by cristianraiber** [comment]
@FreeWPTP - We've isolated the problem & I believe fixed it.

**Comment by ezraholm50** [comment]
How would one go about and test it on a site with content on it already and not breaking it?

**Comment by c0sm1n87** [comment]
@ezraholm50 can you provide a URL to your website (where this issue is happening)?

**Comment by ezraholm50** [comment]
@c0sm1n87 Thank you! Ofcourse, www.promotionbikes.nl

**Comment by c0sm1n87** [comment]
as far as I can see, those parallax sections ( widgets ) are not overlapping in any way. the fix won't break your layout in any way (consider making a backup though, shapely has gone through a major bug fixing session and it's considered a major update). 

You can test the fix by yourself by adding 

    .shapely_home_parallax { display:inline-block; width:100%}

Let me know if there's anything else I can help you with.

**Comment by ezraholm50** [comment]
Well the issue is that its not overlapping but there's blank space between the widgets that is showing the site wide background.

![deepinscreenshot20161215102051](https://cloud.githubusercontent.com/assets/13510720/21218303/51d6289a-c2b0-11e6-9d1b-f72c984e25a1.png)

Any idea when the update will be pushed to the wordpress theme repo's?

**Comment by c0sm1n87** [comment]
this seems to be a different issue ( the parallax plugin used in this theme uses a transparent background to display the "scrollable" image and doing so, it show the image set on body ). I will create another issue and investigate this further
