### ISSUE TITLE
shapely_footer_callout function causing issue 

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/shapely#50]
shapely_footer_callout function causing issue  becauser in the resent theme version the function _e is replaced with esc_attr

Related Topic :

https://colorlib.com/wp/forums/topic/footer-callout-button/#post-76064

Solution :

https://colorlib.com/wp/forums/topic/footer-callout-2/#post-79573

**Comment by cristianraiber** [comment]
@FreeWPTP - All theme mods have to be escaped. That's w.org policy. We're now using `esc_html` which is more appropriate to escape the type of content we're expecting. 

A solution would be to replace esc_html with `wp_kses_post` to allow users to enter limited HTML mark-up in there. @c0sm1n87 - please look into making thi schange.

**Comment by cristianraiber** [comment]
This has been implemented.
