### ISSUE TITLE
Use function get_stylesheet_directory instead of get_template_directory to make the theme child theme ready

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/shapely#51]
Use function get_stylesheet_directory instead of get_template_directory which is use din the following code to make the theme child theme ready.

```
/**
 * WooCoomerce Support
 */
if ( class_exists( 'WooCommerce' ) ) {
    require get_template_directory() . '/inc/woo-setup.php';
}
```

Related Topic :

https://colorlib.com/wp/forums/topic/child-theme-woo-setup-php-override-not-working/

**Comment by cristianraiber** [comment]
@c0sm1n87 - please investigate.

**Comment by cristianraiber** [comment]
@c0sm1n87  - please remove `woo-setup.php` from the theme as all code from this file has been moved inside the companion.

**Comment by cristianraiber** [comment]
File: `woo-setup.php` has been removed from theme files. All it's contents now live inside companion plugin.
