### ISSUE TITLE
esc_attr function returns HTML code as it is

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/shapely#52]
The following esc_attr function used in footer.php file returns HTML code addedin the copyright text field as it is.

`<div class="copyright-text"><?php echo esc_attr(get_theme_mod( 'shapely_footer_copyright' )); ?></div>`

**Comment by cristianraiber** [comment]
@c0sm1n87 - let's replace `esc_html` with `wp_kses_post` to allow minimal HTML entry in here.

**Comment by cristianraiber** [comment]
`esc_attr` has been replaced with `wp_kses_post` which allows minimal HTML entry.
