### ISSUE TITLE
Script/Style Handles

### ISSUE THREAD

**Issue by sakinshrestha** [puikinsh/shapely#54]
* Third party scripts-styles should not have a prefix in handle to stop these files being loaded multiple times. Check `functions.php` function `shapely_scripts()` where you have `shapely-icons, flexslider-css`
* e.g:
 * For font awesome,
    `wp_enqueue_style( 'font-awesome', , get_template_directory_uri().'/inc/css/font-awesome.min.css' );`
* For more info on handle prefix standard, check https://github.com/grappler/wp-standard-handles

**Comment by cristianraiber** [comment]
This has been implemented.
