### ISSUE TITLE
Enqueuing admin scripts

### ISSUE THREAD

**Issue by sakinshrestha** [puikinsh/shapely#56]
* In function `shapely_admin_script()` in `functions.php`, is there any reason you have added `wp_enqueue_media();` outside the `if( $hook == 'widgets.php' || $hook == 'customize.php' )` condition check?
* Currently, media scripts are enqueued in all admin pages, which seems unnecessary, so you need to move the line inside the condition as well

**Comment by justintadlock** [comment]
Also, customize scripts should ideally be loaded via the `customize_controls_enqueue_scripts` hook.

**Comment by justintadlock** [comment]
The same should be said about this function from `inc/extras.php`.  Only add the CSS when it's needed:

```
add_action('admin_head', 'shapely_admin_style');
```

**Comment by cristianraiber** [comment]
@c0sm1n87 - This hasn't been implemented: https://github.com/puikinsh/shapely/issues/56#issuecomment-259281847

**Comment by cristianraiber** [comment]
@c0sm1n87 - let's move this to the companion plugin.

**Comment by cristianraiber** [comment]
This has been moved to the companion plugin. No need to load extra admin CSS for widgets coming from the companion inside the theme.
