### ISSUE TITLE
Custom Logo

### ISSUE THREAD

**Issue by sakinshrestha** [puikinsh/shapely#58]
* From WordPress version 4.5, logo can be added via theme support and in included in core, so you need to use core function rather than adding you own custom version. More info: https://make.wordpress.org/core/2016/03/10/custom-logo/
* Also, in `customizer.php`, I have no idea why you have chosen to use `shapely_sanitize_number` to sanitize `header_logo`

**Comment by cristianraiber** [comment]
@c0sm1n87 - `shapely_sanitize_number` doesn't seem to be used anywhere in the project. Shouldn't we remove it?

**Comment by cristianraiber** [comment]
Function has been removed.
