### ISSUE TITLE
Theme file shapely/js/shapely-scripts.js does not exist

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/shapely#6]
Related topic and the solution :

https://colorlib.com/wp/forums/topic/shapelyjsshapely-scripts-js-is-missing/#post-50161

**Comment by puikinsh** [comment]
Thank you for reporting it! 
It's fixed on https://github.com/puikinsh/shapely/commit/7104a3bc963ae6b19af2eed48b13ecb73c0309e1

**Comment by FreeWPTP** [comment]
Reopened the issue as the following error message occurs on all pages except home page.

`Uncaught TypeError: $(...).flexslider is not a function`

Related Topic :

https://colorlib.com/wp/forums/topic/wp-tiles-and-shapely-issue/#post-51075
