### ISSUE TITLE
Translation ready

### ISSUE THREAD

**Issue by sakinshrestha** [puikinsh/shapely#60]
* Make `Untitled` string in `extras.php` line 58 translation ready
* Make `Default` string in `metaboxes.php` line 66 translation ready

**Comment by justintadlock** [comment]
Line 208 of `inc/customizer.php`:

```
'label' => 'Copyright Text',
```

**Comment by cristianraiber** [comment]
@c0sm1n87 - 

Make Default string in metaboxes.php line 66 translation ready -> not implemented. (https://github.com/puikinsh/shapely/blob/master/inc/metaboxes.php#L66)

**Comment by c0sm1n87** [comment]
https://github.com/c0sm1n87/shapely/commit/d4321444236e66c1a4153c00e4bd7f02408ee56a#diff-91eef6254edbee3ec4611facc8085d51

**Comment by cristianraiber** [comment]
Closing, based on diff. String has been made translatable
