### ISSUE TITLE
Missing Output sanitization/escaping

### ISSUE THREAD

**Issue by sakinshrestha** [puikinsh/shapely#63]
* All values retrieved using `get_theme_mod` and used for output needs to be sanitized properly.
* In `extras.php` function `get_shapely_theme_options`, all options that are outputted needs to be escaped via `esc_attr()` when using using as CSS value
* E.g: Lines 154-156 becomes:

```
    if ( get_theme_mod('social_color')) {
        echo '.social-icons li a {color: ' . esc_attr( get_theme_mod('social_color') ) . ' !important ;}';
      }
```

* In following, `$layout_class` needs to be escaped via `esc_attr`
    * `woo-setup.php` line 67
    * `index.php` line 17
    * `page.php` line 17
    * `search.php` line 14
    * `single.php` line 13
* `extras.php` line 594 `get_theme_mod('blog_name')` needs to be escaped properly maybe `esc_attr` or `esc_html` depending upon your use case. 
* Use `esc_url_raw()` to sanitize input links in `widget-home-call-for-action.php` line 97. `esc_url()` is for sanitizing output links
     * Also in same file, use `esc_attr` to sanitize `$title`, `esc_url` to sanitize `$button_link` in line 37
    * Same issue for links in all widget files in widgets folder
* Need to escape following links using `esc_url()`
    * `extras.php` line 247 `get_the_permalink()`, all instances of `get_pagenum_link()`, line 542 `$logo[0]` used as value for `href=` and `src=`
    * `template-tags.php` line 28 `get_author_posts_url`, line 126 `get_category_link`
    * `widgets/widget-home-clients.php` line 41 `$logos['link'][$i]` and 42 `$logos['img'][$i]`
    * `widgets/widget-home-parallax.php` line 63 `$button2_link`, 64 `$button1_link`, all instances of `$image_src` used as html values
    * `widgets/widget-home-testimonials.php` all instances of`$image_src` used as html values
    * `widgets/widget-recent-posts.php` line 55 get_permalink
    * `woo-setup.php` line 108 `$shop_page_url`, 110 `$cart_url`
* Need to escape following using `esc_attr()`
    * `extras.php` line 247 `get_the_title()`, you can also use `the_title_attribute( 'echo=0' )` function here, line 78 and 293 `get_search_query()`
    * `template-tags.php` line 28 `get_the_author`
    * `woo-setup.php` line 108 `$start_shopping`, 110 `$viewing_cart`

**Comment by justintadlock** [comment]
I don't see it listed above, but you'd want to escape line 291 of `inc/extras.php`.  Wrap `home_url()` with `esc_url()`:

```
$form = '<form role="search" method="get" id="searchform" class="search-form" action="' . home_url( '/' ) . '" >
```

**Comment by justintadlock** [comment]
Line 68 of `inc/metaboxes.php` needs to have the variables escaped:

```
<option value="<?php echo $key; ?>" <?php selected( $layout, $key ); ?> ><?php echo $val; ?></option><?php
```

**Comment by cristianraiber** [comment]
@c0sm1n87 

this doesn't seem to be implemented: https://github.com/puikinsh/shapely/issues/63#issue-187554038
