### ISSUE TITLE
Recommended escaping translation strings

### ISSUE THREAD

**Issue by sakinshrestha** [puikinsh/shapely#64]
* All translation functions must be escaped as sometimes an improper translation may break the html.
* E.g:
    * Almost all instances of `__()`/``_e()`` need to be`esc_html__()`/`esc_html_e()`
        * You have done in most places, but missing in some like function `shapely_search_form`
    * `esc_attr__()` where used as attribute values
        * E.g: in `widget-home-clients.php` line 42 as:
    ```<img alt="<?php esc_attr_e('Logos', 'shapely'); ?>" src="<?php echo esc_url( $logos['img'][$i] ); ?>" />```
        * Also notice escaping image src url
    * passed via `wp_kses()` if some html elements are required

**Comment by cristianraiber** [comment]
@c0sm1n87 - we can ignore the part about the widgets as those have been moved to a companion plugin. But the first part where we should be using `esc_html__()/esc_html_e()` instead of `__` should be implemented.
