### ISSUE TITLE
Modifying User Settings

### ISSUE THREAD

**Issue by sakinshrestha** [puikinsh/shapely#66]
* In `woo-setup.php`, it seems you are modifying user settings using `update_option()`. This is not allowed.

**Comment by justintadlock** [comment]
As a sidenote to this, themes should never auto-add anything to the database upon activation.  Definitely don't overwrite other database options other than theme-specific options.

**Comment by cristianraiber** [comment]
@c0sm1n87 - let's move this into the companion plugin

**Comment by cristianraiber** [comment]
Marking this as invalid as these settings have been moved inside the companion plugin.
