### ISSUE TITLE
Javascript Error

### ISSUE THREAD

**Issue by sakinshrestha** [puikinsh/shapely#68]
* When adding media via Upload Image button in widgets, there is a javascript error when image is added in widgets.
* You will need to trace the issue as it is from `widgets.js` file

**Comment by justintadlock** [comment]
The code is a bit tough to follow, so I couldn't figure out what was causing the JS error.

```
media-upload.js:27 Uncaught TypeError: Cannot read property 'value' of null(…)
```

If you need example media/image upload JS, here's what I've done in a project.  It's Backbone.js-based (same as media views in core WP), but it might be helpful: https://github.com/justintadlock/butterbean/blob/master/js/butterbean.js#L829-L864

**Comment by cristianraiber** [comment]
No more JS errors are being thrown when using the media uploader in widgets. Also, it got a nice little upgrade.

**Comment by cristianraiber** [comment]
@c0sm1n87 - there's a bug with the image not being forced down to a smaller size in the widgets.

![image](https://cloud.githubusercontent.com/assets/7841556/21016595/d12ea096-bd6e-11e6-9475-f2aa51b9ba04.png)

**Comment by c0sm1n87** [comment]
fixed in the plugin :

https://github.com/MachoThemes/shapely-companion/commit/09e647196d22a08572fc8808a1058589e45eeee0#diff-d1caebe36bbae5520fb7ef26f2e7db1d

**Comment by cristianraiber** [comment]
Fixed.
