### ISSUE TITLE
Styling: Media player

### ISSUE THREAD

**Issue by justintadlock** [puikinsh/shapely#75]
When displaying the media player via the `[audio]` or `[video]` shortcode, the player needs some bottom margin to separate it from text or other elements below it.  See screenshot.

![video-shortcode](https://cloud.githubusercontent.com/assets/1816309/20076767/4b35e12a-a4ff-11e6-9c3a-1a017f3284f7.png)

**Comment by cristianraiber** [comment]
This has been implemented.
