### ISSUE TITLE
Styling: Quote tag

### ISSUE THREAD

**Issue by justintadlock** [puikinsh/shapely#79]
It looks like your theme doesn't display quotation marks when the `<q>` tag is used.  This seems to be removed in your CSS, but never added back:

```
blockquote, q {
  quotes: "" "";
}
```

Here's an example for testing:

```
Hey, look here! <q>Developers, developers, developers...</q> That's an inline quote.
```

**Comment by FreeWPTP** [comment]
It seems this is the same case with default WordPress Twenty Sixteen theme.

Please advise.

**Comment by justintadlock** [comment]
It sounds like that should be a bug report with Twenty Sixteen.  I've never reviewed it, so I don't know what all bugs it has.

I'd definitely recommend re-adding the quotes (or not removing them) though so that the tag works correctly.

**Comment by FreeWPTP** [comment]
ok

**Comment by cristianraiber** [comment]
@c0sm1n87 - this doesn't look to be implemented.

**Comment by cristianraiber** [comment]
@c0sm1n87 - let's style the `<q>` tag and make it look like the `<blockquote>` one. 

Current styling:

![image](https://cloud.githubusercontent.com/assets/7841556/21043594/47ecd84c-be00-11e6-9c3f-5a407a048800.png)

---

Blockquote styling:

![image](https://cloud.githubusercontent.com/assets/7841556/21043610/5aca3482-be00-11e6-80f4-c7e0d70d55df.png)

**Comment by justintadlock** [comment]
The `<q>` tag is an inline element, which can be used in the middle of a sentence.  For example:

```
I heard that Justin Tadlock said <q>quote tags are all the rage these days</q>.  But, what do I know?
```

The `<blockquote>` tag is a block-level element.  The styling for it won't work well for inline quotes.

**Comment by cristianraiber** [comment]
@justintadlock - that makes sense. Thanks for the thorough explanation.

**Comment by cristianraiber** [comment]
Implemented.
