### ISSUE TITLE
Escaping: Post title attribute

### ISSUE THREAD

**Issue by justintadlock** [puikinsh/shapely#80]
In `inc/extras.php`, you need to use `the_title_attribute( 'echo=false' )` instead of `get_the_title()` in the following code.  This is breaking my test install, actually. :)

```
function shapely_excerpt_more( $more ) {
	return '<div><a class="btn-filled btn" href="'.get_the_permalink().'" title="'.get_the_title().'">'.esc_html_x( 'Read More', 'Read More', 'shapely' ).'</a></div>';
}
add_filter('excerpt_more', 'shapely_excerpt_more');
```

If you want to see how this can break things, give this a test as a post title:

```
Markup: Title With Special Characters ~`!@#$%^&*()-_=+{}[]/;:'"?,.>
```

Also, change `get_the_permalink()` to `esc_url( get_permalink() )` as noted in: https://github.com/puikinsh/shapely/issues/63

**Comment by cristianraiber** [comment]
This has been implemented.
