### ISSUE TITLE
Loading files

### ISSUE THREAD

**Issue by justintadlock** [puikinsh/shapely#82]
This bit of code from `functions.php` is probably not going to be allowed on .ORG:

```
foreach ( glob( get_template_directory() . '/inc/widgets/*.php' ) as $lib_filename ) {
	require_once( $lib_filename );
}
```

There is slight security concern about loading all files of a folder without knowing what they are.  It's best to simply write out the code directly.

**Comment by cristianraiber** [comment]
@c0sm1n87 - this doesn't seem to be implemented. https://github.com/puikinsh/shapely/blob/master/functions.php#L303-L305

**Comment by c0sm1n87** [comment]
92c5b87848fde9092c4d944f1cc1f54c46440eac

**Comment by cristianraiber** [comment]
This shouldn't have even been in the theme. Moved to companion plugin. Tested.
