### ISSUE TITLE
Don't show unnecessary widgets

### ISSUE THREAD

**Issue by justintadlock** [puikinsh/shapely#83]
When a user doesn't have a plugin installed, such as Jetpack, don't show widgets that only work with that plugin installed, such as the testimonials widget.  This makes for a poor user experience when the user can't figure out why the widget won't work.

**Comment by FreeWPTP** [comment]
If the user don't find these widgets then he may get confused so instead of hiding those widgets until the jetpack plugin install we can display the message in the widget that in order to use this widget please install jetpack plugin and configure it.

Please advise.

**Comment by justintadlock** [comment]
I'd say that it's poor UX for the widget to be added to a sidebar without working.  That's just based on my own experience over the years in UX design.

You also have unnecessary code that's running for users who choose not to install Jetpack or activate that particular module.

A one-time, dismissable admin notice and instructions on your Web site would probably better serve such a feature.

**Comment by FreeWPTP** [comment]
> A one-time, dismissable admin notice and instructions on your Web site would probably better serve such a feature.

It seems better option.

**Comment by cristianraiber** [comment]
We're now showing a notice through the theme's notification system. UX has been improved.
