### ISSUE TITLE
Sanitizing numbers

### ISSUE THREAD

**Issue by justintadlock** [puikinsh/shapely#84]
I noticed this in the testimonials widget, so make sure it's the same anywhere you do it.

First, `esc_html()` is for escaping on output, not for sanitizing input.

Second, use `absint()` for absolute integers (non-negative integers) or `intval()` for any integer (positive or negative).

```
$instance['limit'] = ( ! empty( $new_instance['limit'] ) && is_numeric( $new_instance['limit'] )  ) ? esc_html( $new_instance['limit'] ) : '';
```

**Comment by cristianraiber** [comment]
Code has moved to widgets companion plugin. Issue has been fixed there.
