### ISSUE TITLE
Escaping vs. sanitizing

### ISSUE THREAD

**Issue by justintadlock** [puikinsh/shapely#85]
This is just a general-purpose ticket, so that I'm not opening multiple tickets here for the same thing.

You need to understand the difference between escaping and sanitizing/validating.  I'm seeing a lot of individual issues with the `update()` method for your widgets.

Escaping is for when you want to output something and make sure characters like `'`, `"`, and `>` don't break anything and to prevent XSS issues.  Generally speaking, use the WP `esc_*()` functions for this.

When saving something to the database, however, as in widget `update()` methods, you want to sanitize and/or validate the data before saving.  With the exception of `esc_url_raw()` (used for sanitizing URLs), the WP `esc_*()` functions are not meant for this.

When sanitizing data, you want to make sure it's safe to be stored in the database.  It doesn't need to be escaped.  It needs to be database-safe.  There's a wide range of functions for this and each case depends on the exact type of data that's being input.

Validating data is even better than sanitizing.  Or, at least whitelist-validating data is.  This is when you have a list of acceptable values that are safe to use.  This is usually best with radio, checkbox, and select form fields because it's a limited list of values that are OK.

Here's a couple of links:

* https://codex.wordpress.org/Data_Validation
* https://codex.wordpress.org/Validating_Sanitizing_and_Escaping_User_Data

**Comment by justintadlock** [comment]
Also, see this code from `inc/metaboxes.php`.  Needs to be sanitized and/or validated, not escaped:

```
update_post_meta($post_id, 'site_layout', esc_html( $_POST['site_layout']) );
```

**Comment by cristianraiber** [comment]
@c0sm1n87 - this doesn't seem to be implemented.  https://github.com/puikinsh/shapely/blob/master/inc/metaboxes.php#L104-L106

**Comment by cristianraiber** [comment]
This seems fixed.
