### ISSUE TITLE
Plugin territory: Widget content

### ISSUE THREAD

**Issue by justintadlock** [puikinsh/shapely#86]
The Parralax and Portfolio widgets wouldn't be allowed on .ORG because they allow users to create non-trivial custom content that they will lose when switching themes.

The Portfolio widget could easily be replaced with a text widget.

The Parralax widget could be changed to pull in a page/post instead of having the user create content from the widget itself.

**Comment by cristianraiber** [comment]
These have been moved to a companion plugin.
