### ISSUE TITLE
Plugin territory: kses filter

### ISSUE THREAD

**Issue by justintadlock** [puikinsh/shapely#87]
This filter in `inc/extras.php` is going to be considered plugin territory on .ORG:

```
function shapely_allow_skype_protocol( $protocols ){
    $protocols[] = 'skype';
    return $protocols;
}
add_filter( 'kses_allowed_protocols' , 'shapely_allow_skype_protocol' );
```

It's really borderline, and I understand the reasoning for it.  However, it's something that'll need to be left to plugins.

**Comment by FreeWPTP** [comment]
But the same code is used in the below Sparkling theme which is approved on .ORG

https://wordpress.org/themes/sparkling/

Please advise.

**Comment by justintadlock** [comment]
Most likely, this was overlooked in the review.  It happens.  I can tell you that I don't think any of the TRT admins would approve a filter on any core kses hook though.

**Comment by justintadlock** [comment]
I passed along the issue to a few of the TRT admins.  The consensus seems to be that this is something that should be handled in plugins.

**Comment by FreeWPTP** [comment]
ok

**Comment by cristianraiber** [comment]
This seems to have been removed in the meantime. Closing.
