### ISSUE TITLE
btn-white is replaced with btn-filled in the parallax widget

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/shapely#89]
In the latest version of theme btn-white class is replaced with btn-filled class so both the buttons display filled in the parallax widget but users want one button transparent and other filled.

Related Topic :

https://colorlib.com/wp/forums/topic/darken-parallax-or-make-a-square-around-text/

**Comment by cristianraiber** [comment]
This seems fixed. 

![image](https://cloud.githubusercontent.com/assets/7841556/21045295/7c073d86-be08-11e6-9355-3e5ed1746362.png)
