### ISSUE TITLE
No 'Read More' Button with 'More Tag'

### ISSUE THREAD

**Issue by xenoson** [puikinsh/shapely#90]
As can be seen in the 'Template: More Tag' test content, here the second [blog post](https://colorlib.com/shapely/blog/), the more tag is not showing the 'Read More' button.

**Comment by cristianraiber** [comment]
@c0sm1n87 - please investigate this.

**Comment by cristianraiber** [comment]
Just tested this now. Works just fine. 

![image](https://cloud.githubusercontent.com/assets/7841556/21046000/376cca26-be0b-11e6-8b59-5056e44ab6c7.png)

**Comment by xenoson** [comment]
Now the_excerpt() is out.
We have a 'Continue reading' link for posts with the more tag but full content and no 'Read More' button for other posts on the blog overview (posts page).
Better be consistent with the button.

**Comment by cristianraiber** [comment]
@c0sm1n87 - please investigate this

**Comment by c0sm1n87** [comment]
blog posts are no longer showing excerpt, they are using the_content until a read more tag is found. The excerpt is only used in search pages.

**Comment by xenoson** [comment]
That's good, giving users control via more tag.

**Comment by cristianraiber** [comment]
Looks to me like I can close this, right guys?
